### ISSUE TITLE
Crash when getting a record

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1023]
On the rc1 code release (commit def0d0c), when getting a record I get the following error:

````
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_rest/views.py", line 207, in dispatch_request
    *args, **kwargs
  File "/usr/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/views.py", line 282, in inner
    return f(self, pid=pid, record=record, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/views.py", line 322, in need_record_permission_decorator
    return f(self, record=record, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/views.py", line 556, in get
    pid, record, links_factory=self.links_factory
  File "/usr/lib/python3.4/site-packages/invenio_rest/views.py", line 188, in make_response
    return serializer(*args, **kwargs)
  File "/eudat/b2share/b2share/modules/records/serializers/response.py", line 48, in view
    serializer.serialize(pid, record, links_factory=links_factory)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/serializers/json.py", line 71, in serialize
    self.transform_record(pid, record, links_factory),
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/serializers/marshmallow.py", line 48, in transform_record
    links_factory=links_factory))
  File "/eudat/b2share/b2share/modules/records/serializers/response.py", line 71, in preprocess_record
    pid, record, links_factory)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/serializers/base.py", line 49, in preprocess_record
    links=links_factory(pid),
  File "/eudat/b2share/b2share/modules/records/links.py", line 60, in record_links_factory
    if 'files_bucket_id' in metadata['_internal']:
KeyError: '_internal'
````

**Comment by emanueldima** [comment]
fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/1027
