### ISSUE TITLE
Import a large number of records from b2share site to the testing instance

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1042]
This import should be automatic and (probably) added as a CLI option to the demo. The imported records and files must be marked as open, with a CC-BY or similar license

**Comment by emanueldima** [comment]
see https://github.com/EUDAT-B2SHARE/b2share/pull/1131

**Comment by llehtine** [comment]
Importer is giving this error message:
```
root@591c8c3177d6 b2share]# b2share demo import_v1_data -v -d beLffdEtKxjSSMGLnoGEAQrAAyyEFoISh3F7s8Y3pSrYzVJY4fPPtGsaGWp5 /tmp/b2sharev1
/usr/lib/python3.4/site-packages/dojson/contrib/to_marc21/model.py:22: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
Importing data from b2share.eudat.eu to this instance
----------
Downloading data into directory /tmp/b2sharev1
-----------
Processing 6 files from /tmp/b2sharev1

Traceback (most recent call last):
  File "/eudat/b2share/demo/b2share_demo/helpers.py", line 325, in process_v1_file
    deposit = Deposit.create(record)
  File "/eudat/b2share/b2share/modules/deposit/api.py", line 117, in create
    _external=True
  File "/eudat/b2share/b2share/modules/schemas/serializers.py", line 127, in community_schema_draft_json_schema_link
    community_schema_self_link(community_schema, **kwargs))
  File "/eudat/b2share/b2share/modules/schemas/serializers.py", line 115, in community_schema_self_link
    **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/helpers.py", line 298, in url_for
    raise RuntimeError('Application was not able to create a URL '
RuntimeError: Application was not able to create a URL adapter for request independent URL generation. You might be able to fix this by setting the SERVER_NAME config variable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/b2share", line 11, in <module>
    load_entry_point('b2share', 'console_scripts', 'b2share')()
  File "/usr/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click/core.py", line 1086, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/eudat/b2share/demo/b2share_demo/cli.py", line 130, in import_v1_data
    process_v1_file(f, download, download_directory)
  File "/eudat/b2share/demo/b2share_demo/helpers.py", line 338, in process_v1_file
    current_app.logger.warning("Exception in trying to create deposit for %s" % str(record['title']) + str(record['_deposit']['id']))
KeyError: '_deposit'```

**Comment by emanueldima** [comment]
more comments here: https://github.com/EUDAT-B2SHARE/b2share/pull/1147

**Comment by thijscobben** [comment]
I will create a new issue for "Migration" which is not exactly covered by the spec of this issue to provent "Issue Creep". This issue can be closed.
