### ISSUE TITLE
api: search exception when there exists records with no files

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1073]
To reproduce: create a new record, without any files, then go to the home page. Would be equivalent to creating a new record, and then executing a search.

````
Traceback (most recent call last):
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/werkzeug/wsgi.py", line 659, in __call__
    return app(environ, start_response)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/src/invenio-rest/invenio_rest/views.py", line 207, in dispatch_request
    *args, **kwargs
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/views.py", line 444, in get
    item_links_factory=self.item_links_factory,
  File "/Users/edima/.virtualenvs/b2share-evolution/src/invenio-rest/invenio_rest/views.py", line 188, in make_response
    return serializer(*args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/serializers/response.py", line 70, in view
    item_links_factory=item_links_factory),
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/serializers/json.py", line 88, in serialize_search
    ) for hit in search_result['hits']['hits']],
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/serializers/json.py", line 88, in <listcomp>
    ) for hit in search_result['hits']['hits']],
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/b2share/modules/records/serializers/response.py", line 74, in transform_search_hit
    pid, record_hit, links_factory)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/serializers/marshmallow.py", line 53, in transform_search_hit
    links_factory=links_factory))
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/serializers/base.py", line 64, in preprocess_search_hit
    links=links_factory(pid),
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/b2share/modules/records/links.py", line 60, in record_links_factory
    if 'files_bucket_id' in metadata['_internal']:
KeyError: '_internal'
````

**Comment by emanueldima** [comment]
temporarily fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/1084
