### ISSUE TITLE
docker-compose failed

### ISSUE THREAD

**Issue by Tegomena** [EUDAT-B2SHARE/b2share#1086]
I tried to get the docker version up and running: 

1.)
The file "http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-7.noarch.rpm" no longer exists, I changed the Dockerfile to versin 7.8 (http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm)

2.)
The nginx failed, no file "b2share.conf" anywhere:

Building nginx
Step 1 : FROM nginx
latest: Pulling from library/nginx
51f5c6a04d83: Already exists
a3ed95caeb02: Pull complete
51d229e136d0: Pull complete
bcd41daec8cc: Pull complete
Digest: sha256:0fe6413f3e30fcc5920bc8fa769280975b10b1c26721de956e1428b9e2f29d04
Status: Downloaded newer image for nginx:latest
 ---> 0d409d33b27e
Step 2 : EXPOSE 80 443
 ---> Running in b03e561a3931
 ---> 83d3d2e436a9
Removing intermediate container b03e561a3931
Step 3 : RUN rm /etc/nginx/conf.d/*.conf
 ---> Running in 7675507e517d
 ---> 18e88011879c
Removing intermediate container 7675507e517d
Step 4 : COPY b2share.conf /etc/nginx/conf.d/
ERROR: Service 'nginx' failed to build: lstat b2share.conf: no such file or directory

3.)
Anyway I started the image dockerize_b2share but it seems to hang in an endless loop, there are also lots of Python errors:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/elasticsearch/connection/http_requests.py", line 68, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 471, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.4/site-packages/requests/sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.4/site-packages/requests/adapters.py", line 481, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='elasticsearch', port=9200): Max retries exceeded with url: /marc21-bibliographic-bd-v1.0.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6441dd2240>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/b2share", line 9, in <module>
    load_entry_point('b2share', 'console_scripts', 'b2share')()
  File "/usr/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_search/cli.py", line 61, in init
    for name, response in bar:
  File "/usr/lib/python3.4/site-packages/click/_termui_impl.py", line 257, in next
    return next(self.iter)
  File "/usr/lib/python3.4/site-packages/invenio_search/ext.py", line 150, in create
    for result in _create(self.aliases):
  File "/usr/lib/python3.4/site-packages/invenio_search/ext.py", line 140, in _create
    for result in _create(value, alias=name):
  File "/usr/lib/python3.4/site-packages/invenio_search/ext.py", line 140, in _create
    for result in _create(value, alias=name):
  File "/usr/lib/python3.4/site-packages/invenio_search/ext.py", line 137, in _create
    ignore=ignore,
  File "/usr/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/elasticsearch/client/indices.py", line 105, in create
    params=params, body=body)
  File "/usr/lib/python3.4/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.4/site-packages/elasticsearch/connection/http_requests.py", line 79, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='elasticsearch', port=9200): Max retries exceeded with url: /marc21-bibliographic-bd-v1.0.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6441dd2240>: Failed to establish a new connection: [Errno -2] Name or service not known',))) caused by: ConnectionError(HTTPConnectionPool(host='elasticsearch', port=9200): Max retries exceeded with url: /marc21-bibliographic-bd-v1.0.0 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6441dd2240>: Failed to establish a new connection: [Errno -2] Name or service not known',)))
2016-08-12 10:42:40,615 INFO exited: b2share (exit status 1; not expected)
2016-08-12 10:42:41,617 INFO spawned: 'b2share' with pid 167
^C2016-08-12 10:42:41,721 WARN received SIGINT indicating exit request
2016-08-12 10:42:41,721 INFO waiting for b2share to die
2016-08-12 10:42:41,721 INFO stopped: b2share (terminated by SIGTERM)

**Comment by nharraud** [comment]
As said by email, thank you for your feedback. The current docker image build requires that some scripts are run before calling docker-compose. The installation process [can be seen here](https://github.com/EUDAT-B2SHARE/b2share/blob/evolution/INSTALL.rst).

The deployment process will be improved shortly. We intend to have for the final release a docker image on the docker hub. In the mean time the image build process will be improved so that docker-compose can be used.

The test server which I talked about in the email will be kept up to date with every release candidate.

**Comment by emanueldima** [comment]
Closing, please reopen if necessary.
