### ISSUE TITLE
Deposit search fails internally, deposits vs. deposits-deposits

### ISSUE THREAD

**Issue by janiheikkinen** [EUDAT-B2SHARE/b2share#1299]
Deposit search fails internally in training instance, v.2.0.0rc11 :

GET http://elasticsearch:9200/deposits/deposit/_search?version=true [status:404 request:0.004s]
[2017-01-04 15:17:25,324] ERROR in app: Exception on /records/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.4/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_rest/views.py", line 215, in dispatch_request
    *args, **kwargs
  File "/usr/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/invenio_records_rest/views.py", line 443, in get
    search_result = search.execute()
  File "/usr/lib/python3.4/site-packages/elasticsearch_dsl/search.py", line 627, in execute
    **self._params
  File "/usr/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.4/site-packages/elasticsearch/client/__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python3.4/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.4/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/lib/python3.4/site-packages/elasticsearch/connection/base.py", line 113, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')

GET  http://localhost:9200/deposits-deposits/deposit/_search?version works.

**Comment by emanueldima** [comment]
@janiheikkinen is this the csc training instance? or a local testing instance?

**Comment by janiheikkinen** [comment]
trng-b2share.eudat.eu

**Comment by emanueldima** [comment]
solved by upgrading trng to RC13
