### ISSUE TITLE
demo: load_demo_data fails

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1301]
When installing b2share demo, the load_demo_data function call fails with a FOREIGN KEY constraint error. The breaking change seems to have been introduced in this PR: https://github.com/EUDAT-B2SHARE/b2share/pull/1298 (the error is present in commit #ba5285e but not in #272b17e). The full error log is below.

````
### Add demo config and objects
/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/dojson/contrib/to_marc21/model.py:22: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/dojson/contrib/to_marc21/model.py:22: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
Creating user
Traceback (most recent call last):
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/demo/b2share_demo/helpers.py", line 226, in _create_records
    deposit.publish()
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/b2share/modules/deposit/api.py", line 216, in publish
    return super(Deposit, self).publish(pid=pid, id_=id_)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_deposit/api.py", line 98, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_deposit/api.py", line 344, in publish
    self.commit()
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/b2share/modules/deposit/api.py", line 193, in commit
    community = Community.get(self['community'])
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/b2share/modules/communities/api.py", line 83, in get
    CommunityMetadata.id == id).one()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2754, in one
    ret = self.one_or_none()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2724, in one_or_none
    ret = list(self)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2794, in __iter__
    self.session._autoflush()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1373, in _autoflush
    util.raise_from_cause(e)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1363, in _autoflush
    self.flush()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2137, in flush
    self._flush(objects)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2257, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2221, in _flush
    flush_context.execute()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 176, in save_obj
    mapper, table, insert)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 794, in _emit_insert_statements
    execute(statement, multiparams)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) FOREIGN KEY constraint failed [SQL: 'INSERT INTO records_buckets (record_id, bucket_id) VALUES (?, ?)'] [parameters: (<memory at 0x10bb21d08>, <memory at 0x10ceab1c8>)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/demo/b2share_demo/helpers.py", line 85, in load_demo_data
    _create_records(path, verbose)
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/demo/b2share_demo/helpers.py", line 239, in _create_records
    nb_records += 1
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 559, in __exit__
    self._assert_active(deactive_ok=True, prepared_ok=True)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 285, in _assert_active
    raise sa_exc.ResourceClosedError(closed_msg)
sqlalchemy.exc.ResourceClosedError: This transaction is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/demo/b2share_demo/cli.py", line 66, in load_data
    verbose=verbose)
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/demo/b2share_demo/helpers.py", line 85, in load_demo_data
    _create_records(path, verbose)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 559, in __exit__
    self._assert_active(deactive_ok=True, prepared_ok=True)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 285, in _assert_active
    raise sa_exc.ResourceClosedError(closed_msg)
sqlalchemy.exc.ResourceClosedError: This transaction is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edima/.virtualenvs/b2share-evolution/bin/b2share", line 11, in <module>
    load_entry_point('b2share', 'console_scripts', 'b2share')()
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/core.py", line 1086, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/flask/cli.py", line 229, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/src/b2share/demo/b2share_demo/cli.py", line 66, in load_data
    verbose=verbose)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 559, in __exit__
    self._assert_active(deactive_ok=True, prepared_ok=True)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 285, in _assert_active
    raise sa_exc.ResourceClosedError(closed_msg)
sqlalchemy.exc.ResourceClosedError: This transaction is closed
````

**Comment by nharraud** [comment]
Found the issue. The bug was added by e641860e9e67f2b536c39868cc061db14f20aee5 [here](https://github.com/EUDAT-B2SHARE/b2share/blob/ba5285ef587b7fd43ac3d48b2e200b61637356f7/b2share/modules/records/triggers.py#L63). The code calls the task directly with `index_record(record.id)` instead of calling `index_record.delay(record.id)`. Problem: the later would fail randomly as the celery task might run before the transaction is committed and it wouldn't find the record.
Thus the simplest solution is to directly call `RecordIndexer().index(record)` which will index it synchronously.
I'll create a PR for this.
