### ISSUE TITLE
prod: internal server error on creating new deposits

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1346]
````
[36mb2share_1        |[0m Traceback (most recent call last):
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
[36mb2share_1        |[0m     response = self.full_dispatch_request()
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
[36mb2share_1        |[0m     rv = self.handle_user_exception(e)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
[36mb2share_1        |[0m     reraise(exc_type, exc_value, tb)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
[36mb2share_1        |[0m     raise value
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
[36mb2share_1        |[0m     rv = self.dispatch_request()
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
[36mb2share_1        |[0m     return self.view_functions[rule.endpoint](**req.view_args)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/views.py", line 84, in view
[36mb2share_1        |[0m     return self.dispatch_request(*args, **kwargs)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_rest/views.py", line 215, in dispatch_request
[36mb2share_1        |[0m     *args, **kwargs
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
[36mb2share_1        |[0m     return meth(*args, **kwargs)
[36mb2share_1        |[0m   File "./b2share/modules/records/views.py", line 282, in post
[36mb2share_1        |[0m     record = self.record_class.create(data, id_=record_uuid)
[36mb2share_1        |[0m   File "./b2share/modules/deposit/api.py", line 135, in create
[36mb2share_1        |[0m     deposit = super(Deposit, cls).create(data, id_=id_)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_deposit/api.py", line 70, in wrapper
[36mb2share_1        |[0m     result = method(self_or_cls, *args, **kwargs)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_deposit/api.py", line 244, in create
[36mb2share_1        |[0m     return super(Deposit, cls).create(data, id_=id_)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_records/api.py", line 193, in create
[36mb2share_1        |[0m     record.validate(**kwargs)
[36mb2share_1        |[0m   File "./b2share/modules/deposit/api.py", line 175, in validate
[36mb2share_1        |[0m     return super(Deposit, self).validate(**kwargs)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_records/api.py", line 140, in validate
[36mb2share_1        |[0m     return _records_state.validate(self, self['$schema'], **kwargs)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_records/ext.py", line 58, in validate
[36mb2share_1        |[0m     **kwargs
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 478, in validate
[36mb2share_1        |[0m     cls(schema, *args, **kwargs).validate(instance)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 122, in validate
[36mb2share_1        |[0m     for error in self.iter_errors(*args, **kwargs):
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 98, in iter_errors
[36mb2share_1        |[0m     for error in errors:
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/jsonschema/_validators.py", line 199, in ref
[36mb2share_1        |[0m     scope, resolved = validator.resolver.resolve(ref)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 336, in resolve
[36mb2share_1        |[0m     return url, self._remote_cache(url)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/functools.py", line 472, in wrapper
[36mb2share_1        |[0m     result = user_function(*args, **kwds)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 346, in resolve_from_url
[36mb2share_1        |[0m     raise RefResolutionError(exc)
[36mb2share_1        |[0m jsonschema.exceptions.RefResolutionError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

````

**Comment by emanueldima** [comment]
The production server's certificate does not list all intermediate certificates, so the jsonschema validator throws exception when trying to get the jsonschema from its official https location. This has been verified with curl (also throws ssl error). Some browsers (e.g. Chrome) do recognise the server certificate, likely because they come bundled with a larger list of accepted certificates. The solution is to add the missing intermediate certificate to the ones served by b2share/nginx.

**Comment by emanueldima** [comment]
solved
