### ISSUE TITLE
500 error when submitting abuse report

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1518]
On b2share.eudat.eu there is record with title "test test".
I tried to file an "Abuse report" w data "Not research data" and my personal-data. I saw that a POST was made to the /abuse URL but it generated a 500 server error without further error message.
This has been around 14:20 on July 18th, Amsterdam timezone (for reference to logfiles).
Also tried in authenticated state after logging in: same error.

UI just gave a non-meaningfull error msg but again I saw the 500 from the post to /api/records/<record_id>/abuse

<img width="1127" alt="screenshot 2017-07-18 14 15 31" src="https://user-images.githubusercontent.com/7724267/28316887-ee095ef4-6bc4-11e7-8307-13d5995eed0b.png">

**Comment by emanueldima** [comment]
Production trace:
````
[36mb2share_1        |[0m [2017-08-30 09:12:25,031] ERROR in app: Exception on /records/8e4ef8b58ccf4fb3a0d98e3f4e10d948/abuse [POST]
[36mb2share_1        |[0m Traceback (most recent call last):
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
[36mb2share_1        |[0m     response = self.full_dispatch_request()
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
[36mb2share_1        |[0m     rv = self.handle_user_exception(e)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
[36mb2share_1        |[0m     reraise(exc_type, exc_value, tb)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/_compat.py", line 33, in reraise
[36mb2share_1        |[0m     raise value
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
[36mb2share_1        |[0m     rv = self.dispatch_request()
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
[36mb2share_1        |[0m     return self.view_functions[rule.endpoint](**req.view_args)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/views.py", line 84, in view
[36mb2share_1        |[0m     return self.dispatch_request(*args, **kwargs)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_rest/views.py", line 215, in dispatch_request
[36mb2share_1        |[0m     *args, **kwargs
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask/views.py", line 149, in dispatch_request
[36mb2share_1        |[0m     return meth(*args, **kwargs)
[36mb2share_1        |[0m   File "./b2share/modules/records/views.py", line 372, in post
[36mb2share_1        |[0m     body=msg_content,
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/celery/local.py", line 188, in __call__
[36mb2share_1        |[0m     return self._get_current_object()(*a, **kw)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask_celeryext/app.py", line 60, in __call__
[36mb2share_1        |[0m     res = Task.__call__(self, *args, **kwargs)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/celery/app/task.py", line 428, in __call__
[36mb2share_1        |[0m     return self.run(*args, **kwargs)
[36mb2share_1        |[0m   File "/usr/lib/python3.4/site-packages/invenio_mail/tasks.py", line 47, in send_email
[36mb2share_1        |[0m     current_app.extensions['mail'].send(msg)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask_mail.py", line 491, in send
[36mb2share_1        |[0m     with self.connect() as connection:
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask_mail.py", line 144, in __enter__
[36mb2share_1        |[0m     self.host = self.configure_host()
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/site-packages/flask_mail.py", line 158, in configure_host
[36mb2share_1        |[0m     host = smtplib.SMTP(self.mail.server, self.mail.port)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/smtplib.py", line 242, in __init__
[36mb2share_1        |[0m     (code, msg) = self.connect(host, port)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/smtplib.py", line 321, in connect
[36mb2share_1        |[0m     self.sock = self._get_socket(host, port, self.timeout)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/smtplib.py", line 292, in _get_socket
[36mb2share_1        |[0m     self.source_address)
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/socket.py", line 516, in create_connection
[36mb2share_1        |[0m     raise err
[36mb2share_1        |[0m   File "/usr/lib64/python3.4/socket.py", line 507, in create_connection
[36mb2share_1        |[0m     sock.connect(sa)
[36mb2share_1        |[0m ConnectionRefusedError: [Errno 111] Connection refused
````

It looks like the docker container cannot connect to the smtp server, which I assume by default is localhost.

**Comment by emanueldima** [comment]
relevant link: https://stackoverflow.com/questions/24099453/emails-not-working-in-linux-containers

**Comment by emanueldima** [comment]
moved to https://github.com/EUDAT-B2SHARE/v2-prod-instance/issues/9
solved by setting the following in the b2share.cfg:

#MAIL_SERVER = xxx.xxx.xxxx
#MAIL_USERNAME = ...
#MAIL_PASSWORD = ...
#MAIL_PORT = 25
#MAIL_USE_TLS = True/False
#MAIL_USE_SSL = True/False
#MAIL_DEFAULT_SENDER = ...
