### ISSUE TITLE
Migration error from 2.0.1 to 2.1.0 (SERVER_NAME required?) 

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1577]
Steps to reproduce: 
1. start a b2share dockerized instance (from latest https://github.com/EUDAT-B2SHARE/dockerize), check that UI renders, shut it down (`docker-compose down; docker-compose down`)
2. in `docker-compose.yml`, update b2share image version from `2.0.1` to `2.1.0-rc1`
3. on restarting b2share with `docker-compose up`, the following error is raised:

````
b2share_1        | INFO  [alembic.runtime.migration] Running upgrade 2216c32d7059 -> 1d4e361b7586, Create pidrelations tables.
b2share_1        | Traceback (most recent call last):
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 341, in resolve_from_url
b2share_1        |     document = self.store[url]
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/_utils.py", line 23, in __getitem__
b2share_1        |     return self.store[self.normalize(uri)]
b2share_1        | KeyError: 'https://b2share.local/api/communities/99916f6f-9a2c-4feb-a342-6552ac7f1529/schemas/0'
b2share_1        |
b2share_1        | During handling of the above exception, another exception occurred:
b2share_1        |
b2share_1        | Traceback (most recent call last):
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 344, in resolve_from_url
b2share_1        |     document = self.resolve_remote(url)
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonresolver/contrib/jsonschema.py", line 46, in resolve_remote
b2share_1        |     result = resolver.resolve(uri)
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonresolver/core.py", line 49, in resolve
b2share_1        |     return loader(**args)
b2share_1        |   File "/eudat/b2share/b2share/modules/schemas/jsonresolver.py", line 52, in community_resolver
b2share_1        |     return community_schema_to_dict(community_schema)
b2share_1        |   File "/eudat/b2share/b2share/modules/schemas/serializers.py", line 138, in community_schema_to_dict
b2share_1        |     _external=True)
b2share_1        |   File "/eudat/b2share/b2share/modules/schemas/serializers.py", line 121, in community_schema_json_schema_link
b2share_1        |     community_schema_self_link(community_schema, **kwargs))
b2share_1        |   File "/eudat/b2share/b2share/modules/schemas/serializers.py", line 115, in community_schema_self_link
b2share_1        |     **kwargs)
b2share_1        |   File "/usr/lib64/python3.4/site-packages/flask/helpers.py", line 298, in url_for
b2share_1        |     raise RuntimeError('Application was not able to create a URL '
b2share_1        | RuntimeError: Application was not able to create a URL adapter for request independent URL generation. You might be able to fix this by setting the SERVER_NAME config variable.
b2share_1        |
b2share_1        | During handling of the above exception, another exception occurred:
b2share_1        |
b2share_1        | Traceback (most recent call last):
b2share_1        |   File "/usr/bin/b2share", line 11, in <module>
b2share_1        |     load_entry_point('b2share', 'console_scripts', 'b2share')()
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/core.py", line 716, in __call__
b2share_1        |     return self.main(*args, **kwargs)
b2share_1        |   File "/usr/lib64/python3.4/site-packages/flask/cli.py", line 345, in main
b2share_1        |     return AppGroup.main(self, *args, **kwargs)
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/core.py", line 696, in main
b2share_1        |     rv = self.invoke(ctx)
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
b2share_1        |     return _process_result(sub_ctx.command.invoke(sub_ctx))
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
b2share_1        |     return _process_result(sub_ctx.command.invoke(sub_ctx))
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/core.py", line 889, in invoke
b2share_1        |     return ctx.invoke(self.callback, **ctx.params)
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/core.py", line 534, in invoke
b2share_1        |     return callback(*args, **kwargs)
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
b2share_1        |     return f(get_current_context(), *args, **kwargs)
b2share_1        |   File "/usr/lib64/python3.4/site-packages/flask/cli.py", line 229, in decorator
b2share_1        |     return __ctx.invoke(f, *args, **kwargs)
b2share_1        |   File "/usr/lib/python3.4/site-packages/click/core.py", line 534, in invoke
b2share_1        |     return callback(*args, **kwargs)
b2share_1        |   File "/eudat/b2share/b2share/modules/upgrade/cli.py", line 45, in run
b2share_1        |     upgrade_to_last_version(verbose)
b2share_1        |   File "/eudat/b2share/b2share/modules/upgrade/api.py", line 74, in upgrade_to_last_version
b2share_1        |     upgrade.run(failed_migration=last_failure, verbose=verbose)
b2share_1        |   File "/eudat/b2share/b2share/modules/upgrade/api.py", line 186, in run
b2share_1        |     raise e
b2share_1        |   File "/eudat/b2share/b2share/modules/upgrade/api.py", line 170, in run
b2share_1        |     step.run(alembic, verbose)
b2share_1        |   File "/eudat/b2share/b2share/modules/upgrade/upgrades/upgrade_2_0_0_to_2_1_0.py", line 134, in alembic_upgrade_database_data
b2share_1        |     parent_pid
b2share_1        |   File "/eudat/b2share/b2share/modules/upgrade/upgrades/upgrade_2_0_0_to_2_1_0.py", line 152, in migrate_record_metadata
b2share_1        |     record.commit()
b2share_1        |   File "/eudat/b2share/b2share/modules/deposit/api.py", line 299, in commit
b2share_1        |     super(Deposit, self).commit()
b2share_1        |   File "/usr/lib/python3.4/site-packages/invenio_deposit/api.py", line 72, in wrapper
b2share_1        |     result = method(self_or_cls, *args, **kwargs)
b2share_1        |   File "/usr/lib/python3.4/site-packages/invenio_deposit/api.py", line 206, in commit
b2share_1        |     return super(Deposit, self).commit(*args, **kwargs)
b2share_1        |   File "/usr/lib/python3.4/site-packages/invenio_records/api.py", line 276, in commit
b2share_1        |     self.validate(**kwargs)
b2share_1        |   File "/eudat/b2share/b2share/modules/deposit/api.py", line 247, in validate
b2share_1        |     return super(Deposit, self).validate(**kwargs)
b2share_1        |   File "/usr/lib/python3.4/site-packages/invenio_records/api.py", line 140, in validate
b2share_1        |     return _records_state.validate(self, self['$schema'], **kwargs)
b2share_1        |   File "/usr/lib/python3.4/site-packages/invenio_records/ext.py", line 57, in validate
b2share_1        |     **kwargs
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 478, in validate
b2share_1        |     cls(schema, *args, **kwargs).validate(instance)
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 122, in validate
b2share_1        |     for error in self.iter_errors(*args, **kwargs):
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 98, in iter_errors
b2share_1        |     for error in errors:
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/_validators.py", line 199, in ref
b2share_1        |     scope, resolved = validator.resolver.resolve(ref)
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 336, in resolve
b2share_1        |     return url, self._remote_cache(url)
b2share_1        |   File "/usr/lib64/python3.4/functools.py", line 472, in wrapper
b2share_1        |     result = user_function(*args, **kwds)
b2share_1        |   File "/usr/lib/python3.4/site-packages/jsonschema/validators.py", line 346, in resolve_from_url
b2share_1        |     raise RefResolutionError(exc)
b2share_1        | jsonschema.exceptions.RefResolutionError: Application was not able to create a URL adapter for request independent URL generation. You might be able to fix this by setting the SERVER_NAME config variable.
````

**Comment by emanueldima** [comment]
I tried to continue by defining `B2SHARE_SERVER_NAME='b2share.local'` in docker-compose.yml. After restarting b2share, I got another error: 

````
postgres_1       | ERROR:  duplicate key value violates unique constraint "uq_b2share_migrations_version"
postgres_1       | DETAIL:  Key (version)=(2.1.0) already exists.
postgres_1       | STATEMENT:  INSERT INTO b2share_migrations (created, updated, id, version, data) VALUES ('2017-11-17T14:39:43.760727'::timestamp, '2017-11-17T14:39:43.760737'::timestamp, '6b5cf21d-604b-42cd-81b2-1ad273167ffa'::uuid, '2.1.0', '{"error": null, "status": "start", "steps": []}')
````

**Comment by emanueldima** [comment]
If I define `B2SHARE_SERVER_NAME='b2share.local'` before trying to upgrade, the migration proceeds correctly.

**Comment by nharraud** [comment]
I think the second error happens because of the first failed migration. Cleaning the DB and loading the backup should fix the issue. We can see later how to fix the "migration retry after failure".

Regarding the first error, it seems to me that the JSON Schemas url cannot be resolved. Did you set `B2SHARE_JSONSCHEMAS_HOST`? There should be no need to set `B2SHARE_SERVER_NAME`, I would avoid doing it.

**Comment by nharraud** [comment]
Also note that if this is a migration test for `b2share.eudat.eu`, the records will have records with JSON schema URLs pointing to `b2share.eudat.eu`. Thus the `B2SHARE_JSONSCHEMAS_HOST` should be set to `b2share.eudat.eu`. We don't support yet the change of domain name for a b2share instance.

**Comment by emanueldima** [comment]
`B2SHARE_JSONSCHEMAS_HOST` was correctly set, and the records are all local, created automatically by version 2.0.1.

**Comment by emanueldima** [comment]
not reproducing anymore in 2.1.0
