### ISSUE TITLE
elasticsearch exceptions in prod

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1654]
````
Caused by: SearchParseException[failed to parse search source [{"from": 0, "size": 10, "sort": [{"_created": {"order": "desc"}}], "query": {"bool": {"must": [{"match_all": {}}, {"query_string": {"query": "( community:b344f92a-cd0e-4e4c-aa09-28b5f95f7e41) && publication_state:draft"}}], "should": [{"term": {"_deposit.owners": 589}}, {"bool": {"must": [{"term": {"publication_state": "published"}}, {"term": {"community": "b344f92a-cd0e-4e4c-aa09-28b5f95f7e41"}}]}}, {"bool": {"must": [{"term": {"publication_state": "submitted"}}, {"term": {"community": "b344f92a-cd0e-4e4c-aa09-28b5f95f7e41"}}]}}], "minimum_should_match": 1}}}]]; 
nested: SearchParseException[No mapping found for [_created] in order to sort on];
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:853)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:652)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:618)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:369)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Caused by: SearchParseException[No mapping found for [_created] in order to sort on]
        at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:212)
        at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:186)
        at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:84)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:836)
        ... 10 more
````

**Comment by emanueldima** [comment]
this showed up after a server reboot, seems to be a transient error, closing for now
