### ISSUE TITLE
Elasticsearch error when searching for drafts

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1758]
```sh
elasticsearch_1  | [2020-02-23 15:00:22,165][DEBUG][action.search.type       ] [Surge] [deposits-deposit-v1.0.0][4], node[hx29SyOfQOS3rQX8TK_DBA], [P], v[24], s[STARTED], a[id=9VTWNMFDS1SuyAo8adYVgg]: Failed to execute [org.elasticsearch.action.search.SearchRequest@71c4fcd3] lastShard [true]
elasticsearch_1  | RemoteTransportException[[Surge][172.22.0.2:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from": 0, "query": {"bool": {"minimum_should_match": 1, "must": [{"match_all": {}}, {"query_string": {"query": "(test) && publication_state:draft"}}], "should": [{"term": {"_deposit.owners": 2}}, {"bool": {"must": [{"term": {"publication_state": "submitted"}}, {"term": {"community": "0afede87-2bf2-4d89-867e-d2ee57251c62"}}]}}, {"bool": {"must": [{"term": {"publication_state": "published"}}, {"term": {"community": "0afede87-2bf2-4d89-867e-d2ee57251c62"}}]}}]}}, "size": 10, "sort": [{"_created": {"order": "desc"}}]}]]; nested: SearchParseException[No mapping found for [_created] in order to sort on];
elasticsearch_1  | Caused by: SearchParseException[failed to parse search source [{"from": 0, "query": {"bool": {"minimum_should_match": 1, "must": [{"match_all": {}}, {"query_string": {"query": "(test) && publication_state:draft"}}], "should": [{"term": {"_deposit.owners": 2}}, {"bool": {"must": [{"term": {"publication_state": "submitted"}}, {"term": {"community": "0afede87-2bf2-4d89-867e-d2ee57251c62"}}]}}, {"bool": {"must": [{"term": {"publication_state": "published"}}, {"term": {"community": "0afede87-2bf2-4d89-867e-d2ee57251c62"}}]}}]}}, "size": 10, "sort": [{"_created": {"order": "desc"}}]}]]; nested: SearchParseException[No mapping found for [_created] in order to sort on];
elasticsearch_1  | 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:853)
elasticsearch_1  | 	at org.elasticsearch.search.SearchService.createContext(SearchService.java:652)
elasticsearch_1  | 	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:618)
elasticsearch_1  | 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:369)
elasticsearch_1  | 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
elasticsearch_1  | 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
elasticsearch_1  | 	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
elasticsearch_1  | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
elasticsearch_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elasticsearch_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elasticsearch_1  | 	at java.lang.Thread.run(Thread.java:745)
elasticsearch_1  | Caused by: SearchParseException[No mapping found for [_created] in order to sort on]
elasticsearch_1  | 	at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:212)
elasticsearch_1  | 	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:186)
elasticsearch_1  | 	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:84)
elasticsearch_1  | 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:836)
elasticsearch_1  | 	... 10 more
```

**Comment by hevp** [comment]
Index `deposits-deposit-v1.0.0` is no longer used and does not contain data.
