### ISSUE TITLE
Development installation fails

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#503]
When I try to provision the VM via vagrant I keep getting (below), does anyone know a fix? @emanueldima 
```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/b2share/bin/inveniomanage", line 9, in <module>
    load_entry_point('Invenio==1.9999', 'console_scripts', 'inveniomanage')()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/base/manage.py", line 28, in <module>
    manager = Manager(create_app(), with_default_commands=False)
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/base/factory.py", line 231, in create_app
    app.extensions['registry']['extensions'] = ExtensionRegistry(app)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_registry/registries/appdiscovery.py", line 147, in __init__
    self.register(app, ext_name)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_registry/registries/appdiscovery.py", line 160, in register
    ext(app)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_menu/__init__.py", line 30, in __init__
    self.init_app(app)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_breadcrumbs/__init__.py", line 56, in init_app
    super(Breadcrumbs, self).init_app(app, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_menu/__init__.py", line 39, in init_app
    raise RuntimeError("Flask application is already initialized.")
RuntimeError: Flask application is already initialized.
```

**Comment by emanueldima** [comment]
I think we can close this issue, please reopen if not.
