### ISSUE TITLE
RestAPI request with invalid access_token returns 500

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#547]
RestAPI `GET` request to `/api/records?access_token=kljlkjlksdfj$%^&*(JLKDJFK` returns a HTTP `500`, and the server echoes the trace below. 

_Note: Tests #489 expect a `401` code with JSON payload._

``` log
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py", line 60, in __call__
    response = self.app.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 257, in error_router
    return self.handle_error(e)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 397, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 487, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/ext/restful/__init__.py", line 139, in decorated
    uri, http_method, body, headers, scopes
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 68, in verify_request
    request = Request(uri, http_method, body, headers)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/common.py", line 395, in __init__
    self._params.update(dict(urldecode(self.uri_query)))
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/common.py", line 129, in urldecode
    raise ValueError(error % (set(query) - urlencoded, query))
ValueError: Error trying to decode a non urlencoded string. Found invalid characters: set([u'(', u'$', u'^']) in the string: 'access_token=kljlkjlksdfj$%^&*(JLKDJFK'. Please ensure the request/response body is x-www-form-urlencoded.
127.0.0.1 - - [28/Jan/2015 14:07:36] "GET /api/records/?access_token=kljlkjlksdfj$%%5E&*(JLKDJFK HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py", line 64, in __call__
    response = self.app.handle_exception(e)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 257, in error_router
    return self.handle_error(e)
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py", line 60, in __call__
    response = self.app.full_dispatch_request()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 257, in error_router
    return self.handle_error(e)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 397, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 487, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/ext/restful/__init__.py", line 139, in decorated
    uri, http_method, body, headers, scopes
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 68, in verify_request
    request = Request(uri, http_method, body, headers)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/common.py", line 395, in __init__
    self._params.update(dict(urldecode(self.uri_query)))
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/oauthlib/common.py", line 129, in urldecode
    raise ValueError(error % (set(query) - urlencoded, query))
ValueError: Error trying to decode a non urlencoded string. Found invalid characters: set([u'(', u'$', u'^']) in the string: 'access_token=kljlkjlksdfj$%^&*(JLKDJFK'. Please ensure the request/response body is x-www-form-urlencoded.
```

**Comment by dblommesteijn** [comment]
I've also tried alternate acces_token (without &): `kljlkjlksdfj$%^*(JLKDJFK` yielding the same result.

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
