### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#609]
New pull-requests cannot be checked for issues because Travis is not building since #600. Can someone please fix this so we can make sure our fixes actually work? Thanks.

**Comment by emanueldima** [comment]
https://github.com/EUDAT-B2SHARE/b2share/pull/610 fixes the travis configuration errors, but now there's a new python error in unit tests:

```
  ...
  File "/home/travis/build/emanueldima/b2share/invenio/base/templates/page_base.html", line 39, in block "head_meta"
    <title>{{ title+' - ' if title }}{{ config.CFG_SITE_NAME_INTL[g.ln] }}</title>
  File "/home/travis/build/emanueldima/b2share/invenio/ext/jinja2hacks.py", line 113, in utf8escape
    return jinja2_escape(s)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/markupsafe/__init__.py", line 74, in __new__
    return text_type.__new__(cls, base)
TypeError: object.__new__(Markup) is not safe, use unicode.__new__()
```

**Comment by emanueldima** [comment]
... which seems to be https://github.com/inveniosoftware/invenio/issues/2862

**Comment by jirikuncar** [comment]
Just rebase on `inveniosoftware/invenio@maint-2.0` where it is fixed.

**Comment by emanueldima** [comment]
ok, any idea about this one?:

````
======================================================================
ERROR: test_template_args_loading (invenio.testsuite.test_ext_template.TemplateArgsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/EUDAT-B2SHARE/b2share/invenio/testsuite/test_ext_template.py", line 101, in test_template_args_loading
    self.assertEqual(self.get_context_variable('foo'), 'foo')
  File "/home/travis/build/EUDAT-B2SHARE/b2share/Flask_Testing-0.4.2-py2.7.egg/flask_testing/utils.py", line 186, in get_context_variable
    raise ContextVariableDoesNotExist
ContextVariableDoesNotExist
----------------------------------------------------------------------
````

**Comment by dblommesteijn** [comment]
I've noticed that failed  `test_template_args_loading` before: #470

**Comment by emanueldima** [comment]
Thanks, I did the same

**Comment by dblommesteijn** [comment]
I'm reusing this item te solve the following [error](https://travis-ci.org/EUDAT-B2SHARE/b2share/jobs/57800301):

```
Command "/home/travis/virtualenv/python2.7.9/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-y0ODuM-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-axvaCA-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/virtualenv/python2.7.9/include/site/python2.7" failed with error code 1 in /tmp/pip-y0ODuM-build
The command "pip install . --process-dependency-links --allow-all-external --quiet" failed. Retrying, 2 of 3.
You are using pip version 6.0.7, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by emanueldima** [comment]
remove the --quiet flag on pip install and see what command is pip trying to run

**Comment by dblommesteijn** [comment]
@emanueldima Good idea
