### ISSUE TITLE
Cannot run invenio in VM ('invenio==2.0.1' distribution was not found)

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#613]
When using a VM with rsync synchronization mechanism, after the first install and run of the VM, at subsequent runs, the following error message shows up and invenio cannot run:

````
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/b2share/bin/inveniomanage", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3057, in <module>
    working_set = WorkingSet._build_master()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 639, in _build_master
    ws.require(__requires__)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 940, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 827, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'invenio==2.0.1' distribution was not found and is required by the application
````

**Comment by emanueldima** [comment]
The cause of this issue is that rsync only synchronizes one way, from the host to the VM. During this sync, the `invenio.egg-info` folder in the VM is completely removed. Subsequently, the invenio folder is not recognized as a package anymore, and the error message pops up whenever `inveniomanage` is run. 

One possible solution is to make a copy, right after installation, of the `invenio.egg-info` folder and recopy it to the `invenio` folder whenever necessary. This could be done automatically in the `start_b2share.sh` script.
