### ISSUE TITLE
Cannot run `inveniogc` 

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#663]
The `inveniogc` task should run regularly. Amongst other things, it should clean up the temporary folder users deposit files into. Right now, on a clean VM it fails to run and complains about a missing table. In production, as the database schema is unchanged since older releases, it still runs fine. 

This issue blocks https://github.com/EUDAT-B2SHARE/b2share/issues/592

The log is:
````
2015-06-02 07:18:06 -->
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
    ret = _task_run(task_run_fnc)
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
    if callable(task_run_fnc) and task_run_fnc():
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/websession/inveniogc.py", line 684, in task_run_core
    clean_sessions()
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/websession/inveniogc.py", line 348, in clean_sessions
    deleted_sessions += run_sql(query, (timelimit,))
  File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py", line 268, in run_sql
    rc = cur.execute(sql, param)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'invenio.session' doesn't exist")
2015-06-02 07:18:06 --> Unexpected error occurred: (1146, "Table 'invenio.session' doesn't exist").
2015-06-02 07:18:06 --> Traceback is:
2015-06-02 07:18:06 -->   File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/bibsched/bibtask.py", line 615, in task_init
2015-06-02 07:18:06 -->     ret = _task_run(task_run_fnc)
2015-06-02 07:18:06 -->   File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/bibsched/bibtask.py", line 1191, in _task_run
2015-06-02 07:18:06 -->     if callable(task_run_fnc) and task_run_fnc():
2015-06-02 07:18:06 -->   File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/websession/inveniogc.py", line 684, in task_run_core
2015-06-02 07:18:06 -->     clean_sessions()
2015-06-02 07:18:06 -->   File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/websession/inveniogc.py", line 348, in clean_sessions
2015-06-02 07:18:06 -->     deleted_sessions += run_sql(query, (timelimit,))
2015-06-02 07:18:06 -->   File "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py", line 268, in run_sql
2015-06-02 07:18:06 -->     rc = cur.execute(sql, param)
2015-06-02 07:18:06 -->   File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
2015-06-02 07:18:06 -->     self.errorhandler(self, exc, value)
2015-06-02 07:18:06 -->   File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2015-06-02 07:18:06 -->     raise errorclass, errorvalue
2015-06-02 07:18:06 --> Exiting.
````

**Comment by nharraud** [comment]
I made a pull request for invenio (inveniosoftware/invenio#3220)
Is this fix urgent or can it wait for the merge of invenio maintenance branch?

**Comment by emanueldima** [comment]
I think it can wait, as inveniogc works still fine in production. It will delay https://github.com/EUDAT-B2SHARE/b2share/issues/592, which I don't think is a problem.

**Comment by emanueldima** [comment]
Now it works, as the Invenio package has been upgraded.

**Comment by dblommesteijn** [comment]
Had the same issue with #741
