### ISSUE TITLE
Models generate error message

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#679]
```
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 10:41:52
    last time it was notified: 2015-06-16 10:41:52

* 2015-06-16 10:41:52 -> ValueError: invalid literal for int() with base 16: '' (models.py:109:get)

** User details
                                     agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
                                     email:
                               family_name:
                               given_names:
                                     group: []
                                     guest: 1
                                        id: 0
                                  nickname:
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: False
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <https://b2share.eudat.eu/record/229/export/hx>
                               remote_host:
                                 remote_ip: 194.136.154.133
                                   session: None
                                  settings: {}
                                       uid: 0
                                       uri: </record/229/reviews/add>

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 258, in error_router
    return original_handler(e)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/records/views.py", line 154, in decorated
    return f(recid, *args, **kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py", line 657, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py", line 180, in unauthorized
    return self.unauthorized_callback()
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/login/__init__.py", line 156, in do_login_first
    return login(referer=request.url), 401
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py", line 203, in decorator
    return f(*args, **argd)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/accounts/views/accounts.py", line 75, in login
    action, arguments = mail_cookie_check_authorize_action(action)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/access/mailcookie.py", line 168, in mail_cookie_check_authorize_action
    (kind, params) = mail_cookie_check_common(cookie)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/access/mailcookie.py", line 109, in mail_cookie_check_common
    obj = AccMAILCOOKIE.get(cookie, delete=delete)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/access/models.py", line 109, in get
    cookie_id = int(cookie[16:-16], 16)
ValueError: invalid literal for int() with base 16: ''

** Stack frame details

Frame get in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/access/models.py at line 109
-------------------------------------------------------------------------------
       106     def get(cls, cookie, delete=False):
       107         """Get cookie if it is valid."""
       108         password = cookie[:16]+cookie[-16:]
---->  109         cookie_id = int(cookie[16:-16], 16)
       110
       111         obj, data = db.session.query(
       112             cls,
-------------------------------------------------------------------------------
                         cls =  "<class 'invenio.modules.access.models.AccMAILCOOKIE'>"
                    password =  "u'<*****>'"
                      cookie =  "u'DISPLAY'"
                      delete =  'False'

Frame mail_cookie_check_common in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/access/mailcookie.py at line 109
-------------------------------------------------------------------------------
       106     Return a tuple (kind, params) or <*****> if the cookie is not valid or
       107     it is expired.
       108     """
---->  109     obj = AccMAILCOOKIE.get(cookie, delete=delete)
       110     return (obj.kind, obj.data[1])
       111
       112
-------------------------------------------------------------------------------
                      cookie =  "u'DISPLAY'"
                      delete =  'False'

Frame mail_cookie_check_authorize_action in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/access/mailcookie.py at line 172
-------------------------------------------------------------------------------
       169         assert(kind == 'authorize_action')
       170         return params
       171     except (TypeError, AssertionError):
---->  172         raise InvenioWebAccessMailCookieError
       173
       174
       175 def mail_cookie_delete_cookie(cookie):
-------------------------------------------------------------------------------
                      cookie =  "u'DISPLAY'"

Frame login in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/accounts/views/accounts.py at line 77
-------------------------------------------------------------------------------
        74         try:
        75             action, arguments = mail_cookie_check_authorize_action(action)
        76         except InvenioWebAccessMailCookieError:
---->   77             pass
        78     form = LoginForm(CombinedMultiDict(
        79         [ImmutableMultiDict({'referer': referer, 'login_method': 'Local'}
        80                             if referer else {'login_method': 'Local'}),
-------------------------------------------------------------------------------
        InvenioWebAccessMailCookieError =  "<class 'invenio.modules.access.errors.InvenioWebAccessMailCookieError'>"
                    remember =  'False'
                     referer =  "u'https://b2share.eudat.eu/record/229/reviews/add?action=DISPLAY&ln=e&score=5'"
                      action =  "u'DISPLAY'"
        mail_cookie_check_authorize_action =  '<function mail_cookie_check_authorize_action at 0x7f50372f9050>'
                    password =  '<*****>'
                    nickname =  '<*****>'
                login_method =  "'Local'"

Frame decorator in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py at line 203
-------------------------------------------------------------------------------
       200             from invenio.utils.washers import wash_urlargd
       201             argd = wash_urlargd(request.values, config)
       202             argd.update(kwargs)
---->  203             return f(*args, **argd)
       204         return decorator
       205     return _decorated
-------------------------------------------------------------------------------
                           f =  '<function login at 0x7f50372f9398>'
                        argd =  "{'login_method': 'Local', 'referer': u'https://b2share.eudat.eu/record/229/reviews/add?action=DISPLAY&ln=e&score=5', 'action': u'DISPLAY', 'password': <*****>, 'nickname': <*****>, 'remember': False}"
                        args =  '()'
                      kwargs =  "{'referer': u'https://b2share.eudat.eu/record/229/reviews/add?action=DISPLAY&ln=e&score=5'}"
                wash_urlargd =  '<function wash_urlargd at 0x7f500f64bb18>'
                      config =  "{'login_method': (<function wash_login_method at 0x7f50372eee60>, 'Local'), 'referer': (<type 'unicode'>, <*****>), 'action': (<type 'unicode'>, ''), 'password': (<type 'unicode'>, <*****>), 'nickname': (<type 'unicode'>, <*****>), 'remember': (<type 'bool'>, False)}"

Frame do_login_first in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/login/__init__.py at line 156
-------------------------------------------------------------------------------
       153         if current_user.is_guest:
       154             flash(g._("Please sign in to continue."), 'info')
       155             from invenio.modules.accounts.views.accounts import login
---->  156             return login(referer=request.url), 401
       157         else:
       158             flash(g._("Authorization failure."), 'danger')
       159             from flask import render_template
-------------------------------------------------------------------------------
                       login =  '<function login at 0x7f50372f9320>'
                  secure_url =  "u'https://b2share.eudat.eu/record/229/reviews/add'"
                       error =  '401'

Frame unauthorized in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py at line 180
-------------------------------------------------------------------------------
       177         user_unauthorized.send(current_app._get_current_object())
       178
       179         if self.unauthorized_callback:
---->  180             return self.unauthorized_callback()
       181
       182         if not self.login_view:
       183             abort(401)
-------------------------------------------------------------------------------
                        self =  '<flask_login.LoginManager object at 0x7f5032dd4890>'

Frame decorated_view in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py at line 657
-------------------------------------------------------------------------------
       654         if current_app.login_manager._login_disabled:
       655             return func(*args, **kwargs)
       656         elif not current_user.is_authenticated():
---->  657             return current_app.login_manager.unauthorized()
       658         return func(*args, **kwargs)
       659     return decorated_view
       660
-------------------------------------------------------------------------------
                        args =  '(229,)'
                        func =  '<function add_review at 0x7f5037371e60>'
                      kwargs =  '{}'

Frame decorated in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/records/views.py at line 154
-------------------------------------------------------------------------------
       151             "%s.%s" % (blueprint.name, f.__name__),
       152             recid=recid,
       153         )
---->  154         return f(recid, *args, **kwargs)
       155     return decorated
       156
       157
-------------------------------------------------------------------------------
                           f =  '<function add_review at 0x7f5037371ed8>'
               VIEWRESTRCOLL =  "'viewrestrcoll'"
        guess_primary_collection_of_a_record =  '<function guess_primary_collection_of_a_record at 0x7f500cc4b5f0>'
                    auth_msg =  "''"
        mail_cookie_create_authorize_action =  '<function mail_cookie_create_authorize_action at 0x7f50372f4cf8>'
                        args =  '()'
                       title =  "u'Data Management Trends, Principles and Components - What Needs to be Done Next?'"
                merged_recid =  '<*****>'
                      kwargs =  '{}'
               record_status =  '1'
                  collection =  'Collection <id: 9, name: RDA, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 11>'
            get_merged_recid =  '<function get_merged_recid at 0x7f500cc4b9b0>'
                        tabs =  '[]'
        check_user_can_view_record =  '<function check_user_can_view_record at 0x7f500cc2b7d0>'
                       recid =  '229'
          check_fresh_record =  '<function check_fresh_record at 0x7f500f4755f0>'
                   auth_code =  '0'
                      record =  '{u\'restriction\': {u\'email\': u\'\'}, u\'language_note\': {u\'language_note\': u\'en\'}, u\'abstract\': {u\'summary\': u\'The authors see a number of widely agreed trends about data management emerging and in addition the principles on data as stated for example by G8 ministers seem to be widely accepted. This then asks to take the next steps and investigate which common components need to be specified and put in place to overcome the huge inefficiencies when dealing with data.\'}, u\'fft\':  [...]
              _format_record =  '<function _format_record at 0x7f50000a37d0>'
              record_context =  '<*****>'
               record_exists =  '<function record_exists at 0x7f500c5f9938>'

Frame dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1461
-------------------------------------------------------------------------------
      1458            and req.method == 'OPTIONS':
      1459             return self.make_default_options_response()
      1460         # otherwise dispatch to the handler for that endpoint
----> 1461         return self.view_functions[rule.endpoint](**req.view_args)
      1462
      1463     def full_dispatch_request(self):
      1464         """Dispatches the request and on top of that performs request
-------------------------------------------------------------------------------
                        self =  "<Flask 'invenio.base'>"
                         req =  "<LegacyRequest 'https://b2share.eudat.eu/record/229/reviews/add?action=DISPLAY&ln=e&score=5' [GET]>"
                        rule =  "<Rule '/record/<recid>/reviews/add' (HEAD, POST, OPTIONS, GET) -> comments.add_review>"

Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477
-------------------------------------------------------------------------------
      1474             if rv is <*****>:
      1475                 rv = self.dispatch_request()
      1476         except Exception as e:
----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
      1480         request_finished.send(self, response=response)
-------------------------------------------------------------------------------
                          rv =  '<*****>'
                           e =  'ValueError("invalid literal for int() with base 16: \'\'",)'
                        self =  "<Flask 'invenio.base'>"

Frame handle_user_exception in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1381
-------------------------------------------------------------------------------
      1378             if isinstance(e, typecheck):
      1379                 return handler(e)
      1380
----> 1381         reraise(exc_type, exc_value, tb)
      1382
      1383     def handle_exception(self, e):
      1384         """Default exception handling that kicks in when an exception
-------------------------------------------------------------------------------
                           e =  'ValueError("invalid literal for int() with base 16: \'\'",)'
                    handlers =  '<*****>'
                        self =  "<Flask 'invenio.base'>"
                   exc_value =  'ValueError("invalid literal for int() with base 16: \'\'",)'
          blueprint_handlers =  '()'
                app_handlers =  '()'
                          tb =  '<traceback object at 0x7f50019336c8>'
                    exc_type =  "<type 'exceptions.ValueError'>"

Frame handle_user_exception in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py at line 125
-------------------------------------------------------------------------------
       122         Hook a before handle to it.
       123         """
       124         before_handle_user_exception.send(e)
---->  125         return super(Flask, self).handle_user_exception(e)
       126
       127
       128 def lazy_import(name):
-------------------------------------------------------------------------------
                        self =  "<Flask 'invenio.base'>"
                           e =  'ValueError("invalid literal for int() with base 16: \'\'",)'

Frame error_router in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py at line 258
-------------------------------------------------------------------------------
       255         """
       256         if self._has_fr_route():
       257             return self.handle_error(e)
---->  258         return original_handler(e)
       259
       260     def handle_error(self, e):
       261         """Error handler for the API transforms a raised exception into a Flask
-------------------------------------------------------------------------------
            original_handler =  "<bound method Flask.handle_user_exception of <Flask 'invenio.base'>>"
                        self =  '<flask_restful.Api object at 0x7f5036a01990>'
                           e =  'ValueError("invalid literal for int() with base 16: \'\'",)'

Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477
-------------------------------------------------------------------------------
      1474             if rv is <*****>:
      1475                 rv = self.dispatch_request()
      1476         except Exception as e:
----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
      1480         request_finished.send(self, response=response)
-------------------------------------------------------------------------------
                          rv =  '<*****>'
                           e =  'ValueError("invalid literal for int() with base 16: \'\'",)'
                        self =  "<Flask 'invenio.base'>"

Frame __call__ in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py at line 127
-------------------------------------------------------------------------------
       124                     response = self.app.full_dispatch_request()
       125                 except Exception as e:
       126                     from invenio.ext.logging import register_exception
---->  127                     register_exception(req=request, alert_admin=True)
       128                     response = self.app.handle_exception(e)
       129
       130                 return response(environ, start_response)
-------------------------------------------------------------------------------
              start_response =  '<built-in method start_response of mod_wsgi.Adapter object at 0x7f500ffb4468>'
                     environ =  "{'wsgi.version': (1, 0), 'HTTP_ACUNETIX_ASPECT_PASSWORD': '<*****>', 'mod_wsgi.listener_port': '443', 'HTTP_COOKIE': 'session=5dfe3a7d4bdc4ef299f6309ddc32947f; sessionstub=NO', 'SERVER_SOFTWARE': 'Apache', 'HTTP_ACUNETIX_ASPECT': 'enabled', 'SCRIPT_NAME': '', 'mod_wsgi.enable_sendfile': '0', 'mod_wsgi.handler_script': '', 'SERVER_SIGNATURE': '', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/record/229/reviews/add', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': 'action=DISPLA [...]
                        self =  '<invenio.ext.legacy.LegacyAppMiddleware object at 0x7f5032d52390>'
          register_exception =  '<function register_exception at 0x7f503661a8c0>'
                           e =  'ValueError("invalid literal for int() with base 16: \'\'",)'
```

**Comment by llehtine** [comment]
This is coming when trying to access search-pages with different ln-options, like:
https://b2share.eudat.eu/search?ln=e 
https://b2share.eudat.eu/search?ln=n

When looking on source, those are both defined there as alternates:

  <link rel="canonical" href="http://b2share.eudat.eu/search"/>
  <link rel="alternate" hreflang="e" href="http://b2share.eudat.eu/search?ln=e"/>
  <link rel="alternate" hreflang="n" href="http://b2share.eudat.eu/search?ln=n"/>

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
