### ISSUE TITLE
core.py generates error message

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#680]
```
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 10:15:36
    last time it was notified: 2015-06-16 10:15:36

* 2015-06-16 10:15:36 -> UnknownLocaleError: unknown locale 'e' (core.py:313:parse)

** User details
                                     agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
                                     email:
                               family_name:
                               given_names:
                                     group: []
                                     guest: 1
                                        id: 0
                                  nickname:
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: False
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <https://b2share.eudat.eu/search>
                               remote_host:
                                 remote_ip: 194.136.154.133
                                   session: None
                                  settings: {}
                                       uid: 0
                                       uri: </search>

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 258, in error_router
    return original_handler(e)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py", line 203, in decorator
    return f(*args, **argd)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py", line 149, in decorated
    return method(collection, *args, **kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py", line 468, in search
    easy_search_form=EasySearchForm(csrf_enabled=False),
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/utils/forms.py", line 365, in __init__
    *args, csrf_context=session, **kwargs
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 21, in __init__
    super(SecureForm, self).__init__(formdata, obj, prefix, **kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py", line 346, in bind
    return self.field_class(*self.args, **kw)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py", line 104, in __init__
    self.label = Label(self.id, label if label is not None else self.gettext(_name.replace('_', ' ').title()))
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py", line 160, in gettext
    return self._translations.gettext(string)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_wtf/i18n.py", line 45, in gettext
    t = _get_translations()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_wtf/i18n.py", line 37, in _get_translations
    dirname, [get_locale()], domain='wtforms'
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_babel/__init__.py", line 219, in get_locale
    locale = Locale.parse(rv)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/babel/core.py", line 313, in parse
    raise UnknownLocaleError(input_id)
UnknownLocaleError: unknown locale 'e'

** Stack frame details

Frame parse in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/babel/core.py at line 313
-------------------------------------------------------------------------------
       310             if locale is not None:
       311                 return locale
       312
---->  313         raise UnknownLocaleError(input_id)
       314
       315     def __eq__(self, other):
       316         for key in ('language', 'territory', 'script', 'variant'):
-------------------------------------------------------------------------------
                   _try_load =  '<function _try_load at 0x7f50001bd6e0>'
                  identifier =  "'e'"
                    language =  "'e'"
                      script =  'None'
                      locale =  'None'
                      new_id =  "'e'"
                         sep =  "'_'"
                     variant =  'None'
          _try_load_reducing =  '<function _try_load_reducing at 0x7f50001bd758>'
        resolve_likely_subtags =  'True'
                       parts =  "('e', None, None, None)"
                    input_id =  "'e'"
               likely_subtag =  'None'
                   territory =  'None'
                         cls =  "<class 'babel.core.Locale'>"

Frame get_locale in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_babel/__init__.py at line 219
-------------------------------------------------------------------------------
       216             if rv is None:
       217                 locale = babel.default_locale
       218             else:
---->  219                 locale = Locale.parse(rv)
       220         ctx.babel_locale = locale
       221     return locale
       222
-------------------------------------------------------------------------------
                      locale =  'None'
                       babel =  '<flask_babel.Babel object at 0x7f5031cb8a50>'
                          rv =  "'e'"
                         ctx =  "<RequestContext 'http://b2share.eudat.eu/search?ln=e' [GET] of invenio.base>"

Frame _get_translations in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_wtf/i18n.py at line 37
-------------------------------------------------------------------------------
        34     if translations is None:
        35         dirname = messages_path()
        36         translations = support.Translations.load(
---->   37             dirname, [get_locale()], domain='wtforms'
        38         )
        39         ctx.wtforms_translations = translations
        40     return translations
-------------------------------------------------------------------------------
                         ctx =  "<RequestContext 'http://b2share.eudat.eu/search?ln=e' [GET] of invenio.base>"
                     dirname =  "'/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/locale'"
                translations =  'None'

Frame gettext in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_wtf/i18n.py at line 45
-------------------------------------------------------------------------------
        42
        43 class Translations(object):
        44     def gettext(self, string):
---->   45         t = _get_translations()
        46         if t is None:
        47             return string
        48         if hasattr(t, 'ugettext'):
-------------------------------------------------------------------------------
                        self =  '<flask_wtf.i18n.Translations object at 0x7f5036522a50>'
                      string =  "u'Csrf Token'"

Frame gettext in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py at line 160
-------------------------------------------------------------------------------
       157         :param string: A unicode string to be translated.
       158         :return: A unicode string which is the translated output.
       159         """
---->  160         return self._translations.gettext(string)
       161
       162     def ngettext(self, singular, plural, n):
       163         """
-------------------------------------------------------------------------------
                        self =  '<wtforms.ext.csrf.fields.CSRFTokenField object at 0x7f500f136fd0>'
                      string =  "u'Csrf Token'"

Frame __init__ in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py at line 104
-------------------------------------------------------------------------------
       101         self.validators = validators or list(self.validators)
       102
       103         self.id = id or self.name
---->  104         self.label = Label(self.id, label if label is not None else self.gettext(_name.replace('_', ' ').title()))
       105
       106         if widget is not None:
       107             self.widget = widget
-------------------------------------------------------------------------------
                      widget =  'None'
                       _meta =  'None'
                     default =  'None'
               _translations =  '<flask_wtf.i18n.Translations object at 0x7f5036522a50>'
                     _prefix =  "''"
                        self =  '<wtforms.ext.csrf.fields.CSRFTokenField object at 0x7f500f136fd0>'
                       _name =  "'csrf_token'"
                       _form =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'
                     filters =  '()'
                  validators =  'None'
                       label =  'None'
                          id =  'None'
                 description =  "u''"

Frame bind in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/fields/core.py at line 346
-------------------------------------------------------------------------------
       343             _translations=translations,
       344             **kwargs
       345         )
---->  346         return self.field_class(*self.args, **kw)
       347
       348     def __repr__(self):
       349         return '<UnboundField(%s, %r, %r)>' % (self.field_class.__name__, self.args, self.kwargs)
-------------------------------------------------------------------------------
                        name =  "'csrf_token'"
                        form =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'
                        self =  '<UnboundField(CSRFTokenField, (), {})>'
                translations =  '<flask_wtf.i18n.Translations object at 0x7f5036522a50>'
                      prefix =  "''"
                          kw =  "{'_form': <invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>, '_translations': <flask_wtf.i18n.Translations object at 0x7f5036522a50>, '_prefix': '', '_name': 'csrf_token'}"
                      kwargs =  '{}'

Frame bind_field in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/meta.py at line 27
-------------------------------------------------------------------------------
        24
        25         :return: A bound field
        26         """
---->   27         return unbound_field.bind(form=form, **options)
        28
        29     def wrap_formdata(self, form, formdata):
        30         """
-------------------------------------------------------------------------------
                        self =  '<wtforms.form.Meta object at 0x7f50000b0c50>'
                     options =  "{'prefix': '', 'translations': <flask_wtf.i18n.Translations object at 0x7f5036522a50>, 'name': 'csrf_token'}"
                        form =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'
               unbound_field =  '<UnboundField(CSRFTokenField, (), {})>'

Frame __init__ in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/form.py at line 52
-------------------------------------------------------------------------------
        49
        50         for name, unbound_field in itertools.chain(fields, extra_fields):
        51             options = dict(name=name, prefix=prefix, translations=translations)
---->   52             field = meta.bind_field(self, unbound_field, options)
        53             self._fields[name] = field
        54
        55     def __iter__(self):
-------------------------------------------------------------------------------
                        name =  "'csrf_token'"
                      fields =  "[('csrf_token', <UnboundField(CSRFTokenField, (), {})>), ('author', <UnboundField(AutocompleteField, (lu'Author',), {'data_source': <function <lambda> at 0x7f503721fb18>, 'data_provide': 'typeahead-url'})>), ('title', <UnboundField(StringField, (lu'Title',), {})>), ('rn', <UnboundField(AutocompleteField, (lu'Report number',), {'data_source': <function <lambda> at 0x7f503721fb90>, 'data_provide': 'typeahead-url'})>), ('aff', <UnboundField(AutocompleteField, (lu'Affiliation',), {'data_source': <f [...]
                extra_fields =  '[]'
                translations =  '<flask_wtf.i18n.Translations object at 0x7f5036522a50>'
                        self =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'
                      prefix =  "''"
                        meta =  '<wtforms.form.Meta object at 0x7f50000b0c50>'
                     options =  "{'prefix': '', 'translations': <flask_wtf.i18n.Translations object at 0x7f5036522a50>, 'name': 'csrf_token'}"
               unbound_field =  '<UnboundField(CSRFTokenField, (), {})>'

Frame __init__ in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/form.py at line 272
-------------------------------------------------------------------------------
       269         meta_obj = self._wtforms_meta()
       270         if meta is not None and isinstance(meta, dict):
       271             meta_obj.update_values(meta)
---->  272         super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
       273
       274         for name, field in iteritems(self._fields):
       275             # Set all the fields to attributes so that they obscure the class
-------------------------------------------------------------------------------
                    meta_obj =  '<wtforms.form.Meta object at 0x7f50000b0c50>'
                         obj =  'None'
                    formdata =  'None'
                      prefix =  "''"
                        meta =  'None'
                      kwargs =  '{}'
                        data =  'None'
                        self =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'

Frame __init__ in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/ext/csrf/form.py at line 21
-------------------------------------------------------------------------------
        18             Optional extra data which is passed transparently to your
        19             CSRF implementation.
        20         """
---->   21         super(SecureForm, self).__init__(formdata, obj, prefix, **kwargs)
        22         self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
        23
        24     def generate_csrf_token(self, csrf_context):
-------------------------------------------------------------------------------
                         obj =  'None'
                    formdata =  'None'
                        self =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'
                      prefix =  "''"
                      kwargs =  '{}'
                csrf_context =  '{}'

Frame __init__ in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_wtf/form.py at line 96
-------------------------------------------------------------------------------
        93             self.SECRET_KEY = ''
        94         super(Form, self).__init__(formdata, obj, prefix,
        95                                    csrf_context=csrf_context,
---->   96                                    *args, **kwargs)
        97
        98     def generate_csrf_token(self, csrf_context=None):
        99         if not self.csrf_enabled:
-------------------------------------------------------------------------------
                         obj =  'None'
                csrf_context =  '{}'
                        args =  '()'
                        self =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'
                      prefix =  "''"
                      kwargs =  '{}'
                  secret_key =  'None'
                csrf_enabled =  'False'
                    formdata =  'None'

Frame __init__ in /var/www/.virtualenvs/b2share/src/b2share/invenio/utils/forms.py at line 365
-------------------------------------------------------------------------------
       362     def __init__(self, *args, **kwargs):
       363         """Init."""
       364         super(InvenioBaseForm, self).__init__(
---->  365             *args, csrf_context=session, **kwargs
       366         )
       367
       368     def add_fields(self, name, field):
-------------------------------------------------------------------------------
                        self =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f50000b0310>'
                        args =  '()'
                      kwargs =  "{'csrf_enabled': False}"

Frame __call__ in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/wtforms/form.py at line 212
-------------------------------------------------------------------------------
       209                 if 'Meta' in mro_class.__dict__:
       210                     bases.append(mro_class.Meta)
       211             cls._wtforms_meta = type('Meta', tuple(bases), {})
---->  212         return type.__call__(cls, *args, **kwargs)
       213
       214     def __setattr__(cls, name, value):
       215         """
-------------------------------------------------------------------------------
                         cls =  "<class 'invenio.modules.search.forms.EasySearchForm'>"
                        args =  '()'
                      kwargs =  "{'csrf_enabled': False}"

Frame search in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py at line 468
-------------------------------------------------------------------------------
       465         records=len(get_current_user_records_that_can_be_displayed(qid)),
       466         qid=qid, rg=rg,
       467         create_nearest_terms_box=lambda: _create_neareset_term_box(argd_orig),
---->  468         easy_search_form=EasySearchForm(csrf_enabled=False),
       469         ot=ot
       470     )
       471
-------------------------------------------------------------------------------
                   argd_orig =  "{'em': '', 'f1': '', 'f2': '', 'f3': '', 'op1': '', 'op2': '', 'cc': u'B2Share', 'ec': [], 'ap': 1, 'd2': '', 'id': -1, 'd1': '', 'd2y': 0, 'sysnb': '', 'jrec': 0, 'ln': 'e', 'sysno': '', 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd2d': 0, 'wl': 50000, 'action': 'search', 'rm': '', 'verbose': 0, 'dt': '', 'p2': '', 'p3': '', 'c': [], 'p1': '', 'so': 'd', 'f': '', 'of': 'id', 'sp': '', 'd1y': 0, 'd1d': 0, 'p': '', 'recid': -1, 'aas': 0, 'recidb': -1, 'sc': 0, 'd1m': 0, 'ot': [], 'idb': - [...]
        perform_request_search =  '<function perform_request_search at 0x7f500cc4c7d0>'
                      recids =  '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]'
                         qid =  "'7fe42195e07b36366776e3e7049a6362'"
             last_query_hits =  '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]'
                  collection =  'Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 225>'
                           p =  "''"
                          rg =  '10'
                          so =  'None'
                   hit_limit =  '1000'
                          of =  "u'hb'"
                          rm =  'None'
                          ot =  'None'
                        argd =  "{'em': '', 'f1': '', 'f2': '', 'f3': '', 'op1': '', 'op2': '', 'cc': u'B2Share', 'ec': [], 'ap': 1, 'd2': '', 'id': -1, 'd1': '', 'd2y': 0, 'sysnb': '', 'jrec': 0, 'ln': 'e', 'sysno': '', 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd2d': 0, 'wl': 50000, 'action': 'search', 'rm': '', 'verbose': 0, 'dt': '', 'p2': '', 'p3': '', 'c': [], 'p1': '', 'so': 'd', 'f': '', 'of': 'id', 'sp': '', 'd1y': 0, 'd1d': 0, 'p': '', 'recid': -1, 'aas': 0, 'recidb': -1, 'sc': 0, 'd1m': 0, 'ot': [], 'idb': - [...]

Frame decorated in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py at line 149
-------------------------------------------------------------------------------
       146             elif auth_code:
       147                 return abort(401)
       148
---->  149         return method(collection, *args, **kwargs)
       150     return decorated
       151
       152
-------------------------------------------------------------------------------
                        name =  'None'
                        args =  '()'
                  collection =  'Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 225>'
                 name_getter =  '<function collection_name_from_request at 0x7f5037c57938>'
                      kwargs =  "{'p': '', 'ot': None, 'so': None, 'rm': None, 'of': u'hb'}"
          default_collection =  'True'
                      method =  '<function search at 0x7f5037c5af50>'
                         uid =  '0'

Frame decorator in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py at line 203
-------------------------------------------------------------------------------
       200             from invenio.utils.washers import wash_urlargd
       201             argd = wash_urlargd(request.values, config)
       202             argd.update(kwargs)
---->  203             return f(*args, **argd)
       204         return decorator
       205     return _decorated
-------------------------------------------------------------------------------
                           f =  '<function search at 0x7f5037c5d050>'
                        argd =  "{'p': '', 'of': u'hb', 'ot': None, 'so': None, 'rm': None}"
                        args =  '()'
                      kwargs =  '{}'
                wash_urlargd =  '<function wash_urlargd at 0x7f500f64bb18>'
                      config =  "{'p': (<type 'unicode'>, ''), 'ot': (<type 'unicode'>, None), 'so': (<type 'unicode'>, None), 'rm': (<type 'unicode'>, None), 'of': (<type 'unicode'>, u'hb')}"

Frame dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1461
-------------------------------------------------------------------------------
      1458            and req.method == 'OPTIONS':
      1459             return self.make_default_options_response()
      1460         # otherwise dispatch to the handler for that endpoint
----> 1461         return self.view_functions[rule.endpoint](**req.view_args)
      1462
      1463     def full_dispatch_request(self):
      1464         """Dispatches the request and on top of that performs request
-------------------------------------------------------------------------------
                        self =  "<Flask 'invenio.base'>"
                         req =  "<LegacyRequest 'http://b2share.eudat.eu/search?ln=e' [GET]>"
                        rule =  "<Rule '/search' (HEAD, POST, OPTIONS, GET) -> search.search>"

Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477
-------------------------------------------------------------------------------
      1474             if rv is None:
      1475                 rv = self.dispatch_request()
      1476         except Exception as e:
----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
      1480         request_finished.send(self, response=response)
-------------------------------------------------------------------------------
                          rv =  'None'
                           e =  'UnknownLocaleError("unknown locale \'e\'",)'
                        self =  "<Flask 'invenio.base'>"

Frame handle_user_exception in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1381
-------------------------------------------------------------------------------
      1378             if isinstance(e, typecheck):
      1379                 return handler(e)
      1380
----> 1381         reraise(exc_type, exc_value, tb)
      1382
      1383     def handle_exception(self, e):
      1384         """Default exception handling that kicks in when an exception
-------------------------------------------------------------------------------
                           e =  'UnknownLocaleError("unknown locale \'e\'",)'
                    handlers =  'None'
                        self =  "<Flask 'invenio.base'>"
                   exc_value =  'UnknownLocaleError("unknown locale \'e\'",)'
          blueprint_handlers =  '()'
                app_handlers =  '()'
                          tb =  '<traceback object at 0x7f500f99bab8>'
                    exc_type =  "<class 'babel.core.UnknownLocaleError'>"

Frame handle_user_exception in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py at line 125
-------------------------------------------------------------------------------
       122         Hook a before handle to it.
       123         """
       124         before_handle_user_exception.send(e)
---->  125         return super(Flask, self).handle_user_exception(e)
       126
       127
       128 def lazy_import(name):
-------------------------------------------------------------------------------
                        self =  "<Flask 'invenio.base'>"
                           e =  'UnknownLocaleError("unknown locale \'e\'",)'

Frame error_router in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py at line 258
-------------------------------------------------------------------------------
       255         """
       256         if self._has_fr_route():
       257             return self.handle_error(e)
---->  258         return original_handler(e)
       259
       260     def handle_error(self, e):
       261         """Error handler for the API transforms a raised exception into a Flask
-------------------------------------------------------------------------------
            original_handler =  "<bound method Flask.handle_user_exception of <Flask 'invenio.base'>>"
                        self =  '<flask_restful.Api object at 0x7f5036a01990>'
                           e =  'UnknownLocaleError("unknown locale \'e\'",)'

Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477
-------------------------------------------------------------------------------
      1474             if rv is None:
      1475                 rv = self.dispatch_request()
      1476         except Exception as e:
----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
      1480         request_finished.send(self, response=response)
-------------------------------------------------------------------------------
                          rv =  'None'
                           e =  'UnknownLocaleError("unknown locale \'e\'",)'
                        self =  "<Flask 'invenio.base'>"

Frame __call__ in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py at line 127
-------------------------------------------------------------------------------
       124                     response = self.app.full_dispatch_request()
       125                 except Exception as e:
       126                     from invenio.ext.logging import register_exception
---->  127                     register_exception(req=request, alert_admin=True)
       128                     response = self.app.handle_exception(e)
       129
       130                 return response(environ, start_response)
-------------------------------------------------------------------------------
              start_response =  '<built-in method start_response of mod_wsgi.Adapter object at 0x7f5000bd0e40>'
                     environ =  "{'wsgi.version': (1, 0), 'HTTP_ACUNETIX_ASPECT_PASSWORD': '<*****>', 'mod_wsgi.listener_port': '80', 'HTTP_COOKIE': 'session=5dfe3a7d4bdc4ef299f6309ddc32947f; sessionstub=NO', 'SERVER_SOFTWARE': 'Apache', 'HTTP_ACUNETIX_ASPECT': 'enabled', 'SCRIPT_NAME': '', 'mod_wsgi.enable_sendfile': '0', 'mod_wsgi.handler_script': '', 'SERVER_SIGNATURE': '', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/search', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': 'ln=e', 'HTTP_USER_AGENT': 'Moz [...]
                        self =  '<invenio.ext.legacy.LegacyAppMiddleware object at 0x7f5032d52390>'
          register_exception =  '<function register_exception at 0x7f503661a8c0>'
                           e =  'UnknownLocaleError("unknown locale \'e\'",)'
```

**Comment by llehtine** [comment]
Bit same as https://github.com/EUDAT-B2SHARE/b2share/issues/679, i'll close this one, as I guess they are same issue.
