### ISSUE TITLE
Problems viewing mpeg-video which is uploaded to the record.

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#683]
```
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 11:06:33
    last time it was notified: 2015-06-16 11:06:33

* 2015-06-16 11:06:33 -> InvenioBibDocFileError: No file for doc 70 of format '.mpeg&download=1', version '' (api.py:2545:get_file)

** User details
                                     agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
                                     email:
                               family_name:
                               given_names:
                                     group: []
                                     guest: 1
                                        id: 0
                                  nickname:
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: False
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <https://test-eudatis.csc.fi/record/31>
                               remote_host:
                                 remote_ip: 194.136.154.133
                                   session: None
                                  settings: {}
                                       uid: 0
                                       uri: </record/31/files/b22be5aa-8220-11e3-9e22-00505694536b.mpeg&download=1>

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/bibdocfile/webinterface.py", line 194, in getfile
    docfile = doc.get_file(docformat, version)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/bibdocfile/api.py", line 2545, in get_file
    raise InvenioBibDocFileError("No file for doc %i of format '%s', version '%s'" % (self.id, docformat, version))
InvenioBibDocFileError: No file for doc 70 of format '.mpeg&download=1', version ''

** Stack frame details

Frame get_file in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/bibdocfile/api.py at line 2545
-------------------------------------------------------------------------------
      2542                 if get_superformat_from_format(docfile.get_format()) == superformat:
      2543                     return docfile
      2544
----> 2545         raise InvenioBibDocFileError("No file for doc %i of format '%s', version '%s'" % (self.id, docformat, version))
      2546
      2547     def list_versions(self):
      2548         """
-------------------------------------------------------------------------------
                    docfiles =  '[BibDocFile(\'/var/www/.virtualenvs/b2share/var/data/files/g0/70/file.mpeg;1\',  1, \'b22be5aa-8220-11e3-9e22-00505694536b\', \'.mpeg\', 31, 70, \'firerole: allow any\\n\', \'da02bc155e0835ebfee05642f0ee6582\', BibDocMoreInfo(70, "ccopy_reg\\n_reconstructor\\np1\\n(cinvenio.legacy.bibdocfile.api\\nBibDocMoreInfo\\np2\\nc__builtin__\\nobject\\np3\\nNtRp4\\n(dp5\\nS\'cache_reads\'\\np6\\nI01\\nsS\'docid\'\\np7\\nI70\\nsS\'format\'\\np8\\nNsS\'cache\'\\np9\\n(dp10\\nS\'\'\\n(dp11\\nS\'flags\'\\np1 [...]
             exact_docformat =  'False'
                   docformat =  "'.mpeg&download=1'"
                        self =  "BibDoc(70, 'Main', False)"
                     docfile =  'BibDocFile(\'/var/www/.virtualenvs/b2share/var/data/files/g0/70/file.mpeg;1\',  1, \'b22be5aa-8220-11e3-9e22-00505694536b\', \'.mpeg\', 31, 70, \'firerole: allow any\\n\', \'da02bc155e0835ebfee05642f0ee6582\', BibDocMoreInfo(70, "ccopy_reg\\n_reconstructor\\np1\\n(cinvenio.legacy.bibdocfile.api\\nBibDocMoreInfo\\np2\\nc__builtin__\\nobject\\np3\\nNtRp4\\n(dp5\\nS\'cache_reads\'\\np6\\nI01\\nsS\'docid\'\\np7\\nI70\\nsS\'format\'\\np8\\nNsS\'cache\'\\np9\\n(dp10\\nS\'\'\\n(dp11\\nS\'flags\'\\np12 [...]
                     version =  "''"
                 superformat =  "'.mpeg&download=1'"

Frame getfile in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/bibdocfile/webinterface.py at line 200
                         uid =  '0'
                 is_download =  'False'
                     verbose =  '0'
                          ln =  "'en'"
                        self =  '<invenio.legacy.bibdocfile.webinterface.WebInterfaceFilesPages object at 0x7fe8cf718950>'
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7fe8cf718ed0>'
                    filename =  "'b22be5aa-8220-11e3-9e22-00505694536b.mpeg&download=1'"
                   user_info =  "UserInfo([{'referer': 'https://test-eudatis.csc.fi/record/31', 'remote_host': '', 'uri': '/record/31/files/b22be5aa-8220-11e3-9e22-00505694536b.mpeg&download=1', 'agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36', 'remote_ip': '194.136.154.133'}, <CallbackDict {'settings': {}, 'uid': 0, 'id': 0}>, {}, {'precached_usestats': False, 'precached_usemessages': False, 'uid': -1, 'agent': '', 'uri': '', 'precached_usegroups': False, [...]
                    readonly =  'False'
                     version =  "''"
                   auth_code =  '0'
                         msg =  'InvenioBibDocFileError("No file for doc 70 of format \'.mpeg&download=1\', version \'\'",)'
                        form =  '{}'
                        args =  "{'verbose': 0, 'format': '', 'ln': 'en', 'docname': '', 'subformat': '', 'version': '', 'download': 0}"
                        warn =  "''"
                     docname =  "'b22be5aa-8220-11e3-9e22-00505694536b'"
                           _ =  '<function unicode_gettext_wrapper at 0x7fe8c50a9230>'
                  bibarchive =  'BibRecDocs(31)'
                   docformat =  "'.mpeg&download=1'"
                         doc =  "BibDoc(70, 'Main', False)"
              display_hidden =  'False'
                auth_message =  "''"'
```

**Comment by llehtine** [comment]
Apparently if you upload vdeo to B2Share (like there is on test-environment upload https://test-eudatis.csc.fi/record/30 and https://test-eudatis.csc.fi/record/31 you get the video showing up on the page. It also should generate some links there where you can download it, but when I've looked to at HTML the links seems to be wrong (in record 31 case it's written as /record/31/files/b22be5aa-8220-11e3-9e22-00505694536b.mpeg&download=1 and should be /record/31/files/b22be5aa-8220-11e3-9e22-00505694536b.mpeg?download=1) But on Firefox atleast the viewing of video didn't seem to work.

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
