### ISSUE TITLE
templates.py giving error message

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#684]
```
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 11:16:01
    last time it was notified: 2015-06-16 11:16:01

* 2015-06-16 11:16:01 -> TypeError: argument of type 'int' is not iterable (templates.py:3915:tmpl_display_back_to_search)

** User details
                                     agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
                                     email:
                               family_name:
                               given_names:
                                     group: []
                                     guest: 1
                                        id: 0
                                  nickname:
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: False
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <None>
                               remote_host:
                                 remote_ip: 194.136.154.133
                                   session: None
                                  settings: {}
                                       uid: 0
                                       uri: </record/112/export>

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/handler.py", line 337, in _handler
    return root._traverse(req, path, False, guest_p)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/handler.py", line 241, in _traverse
    return obj._traverse(req, path, do_head, guest_p)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/handler.py", line 252, in _traverse
    result = _check_result(req, obj(req, form))
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/websearch/webinterface.py", line 1184, in __call__
    out = perform_request_search(req, **argd)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 5718, in perform_request_search
    return prs_perform_search(kwargs=kwargs, **kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 5729, in prs_perform_search
    return prs_search(kwargs=kwargs, **kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 5889, in prs_search
    output = prs_detailed_record(kwargs=kwargs, **kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 5953, in prs_detailed_record
    so=so, sp=sp, rm=rm, em=em, nb_found=len(range(recid, recidb)))
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 4954, in print_records
    ln)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/websearch/templates.py", line 3915, in tmpl_display_back_to_search
    if recID in coll:
TypeError: argument of type 'int' is not iterable

** Stack frame details

Frame tmpl_display_back_to_search in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/websearch/templates.py at line 3915
-------------------------------------------------------------------------------
      3912         # let's look for the recID's collection
      3913         record_found = False
      3914         for coll in wlqh:
----> 3915             if recID in coll:
      3916                 record_found = True
      3917                 coll_recID = coll
      3918                 break
-------------------------------------------------------------------------------
                          ln =  "'en'"
                         wlq =  "'/search?box=simple&of=hb&p=1&rg=25&rm=citation'"
                        self =  '<invenio.legacy.websearch.templates.Template instance at 0x7f1898920878>'
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                        wlqh =  '[1, 6, 15, 16, 23, 25, 26, 43, 55, 88]'
                record_found =  'False'
                        coll =  '1'
                       recID =  '112'
                           _ =  '<function unicode_gettext_wrapper at 0x7f1890791a28>'
                         out =  '\'<br/><br/><div align="right">\''

Frame print_records in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 4954
                          em =  "''"
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                     verbose =  '0'
                    irec_max =  '0'
                        tabs =  "[('Information', '/record/112/', True, True), ('References', '/record/112/references', False, True), ('Citations', '/record/112/citations', False, True), ('Keywords', '/record/112/keywords', False, True), ('Comments', '/record/112/comments', False, True), ('Usage statistics', '/record/112/usage', False, True), ('Files', '/record/112/files', False, True), ('Plots', '/record/112/plots', False, False)]"
         relevances_epilogue =  "'%%)'"
                  references =  '0'
                         tab =  "''"
                 discussions =  '0'
                 tabs_counts =  "{'Discussions': 0, 'Reviews': 0, 'Citations': 0, 'References': 0, 'Comments': 0}"
                        jrec =  '1'
                      recIDs =  '[112]'
                          ln =  "'en'"
                          sf =  "''"
                      format =  "'hd'"
                  citedbynum =  '0'
                     content =  '\'<abbr class="unapi-id" title="112"></abbr>\\n\\n\\n\\n\\n<div class="record-detailed">\\n\\n  <div class="record-header">\\n    \\n    \\n    MMX\\n\\n  </div>\\n\\n  <div class="record-details">\\n    \\n    <a href="/search?f=author&amp;p=Intel&amp;ln=en">Intel</a><br />\\n    \\n    \\n    <br />26 March 2015<br />\\n    <small>https://trng-b2share.eudat.eu</small>\\n    \\n    \\n\\n  </div>\\n\\n  <div class="record-abstract">\\n    \\n    <small><strong>Abstract: </strong>Intel MMX inst [...]
                   user_info =  "UserInfo([{'referer': None, 'remote_host': '', 'uri': '/record/112/export', 'agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36', 'remote_ip': '194.136.154.133'}, <CallbackDict {'settings': {}, 'uid': 0, 'id': 0}>, {}, {'precached_usestats': False, 'precached_usemessages': False, 'uid': -1, 'agent': '', 'uri': '', 'precached_usegroups': False, 'session': None, 'referer': '', 'precached_canseehiddenmarctags': False, 'precached_u [...]
                          rg =  '1'
            modificationdate =  "'2015-04-29'"
                      tab_id =  "'hepdata'"
        print_records_prologue_p =  'True'
                     link_ln =  "''"
                    nb_found =  '1'
                  decompress =  '<built-in function decompress>'
        print_records_epilogue_p =  'True'
         relevances_prologue =  "'('"
                     referer =  'None'
                          rm =  "''"
                           _ =  '<function unicode_gettext_wrapper at 0x7f1890791d70>'
                          ot =  '[]'
                    irec_min =  '-1'
                      values =  "{'visible': True, 'enabled': True, 'order': 7, 'label': 'Usage statistics'}"
                          sp =  "''"
            recid_to_display =  '112'
                          so =  "'d'"
             ordered_tabs_id =  "[('', 1), ('references', 2), ('citations', 3), ('keywords', 4), ('comments', 5), ('reviews', 6), ('usage', 7), ('files', 8), ('plots', 9), ('holdings', 10), ('linkbacks', 11), ('hepdata', 12)]"
                 dummy_order =  '12'
                       recid =  '112'
                  relevances =  '[]'
              search_pattern =  "''"
                creationdate =  "'2015-03-26'"
              unordered_tabs =  "{'files': {'visible': True, 'enabled': True, 'order': 8, 'label': 'Files'}, '': {'visible': True, 'enabled': True, 'order': 1, 'label': 'Information'}, 'references': {'visible': True, 'enabled': True, 'order': 2, 'label': 'References'}, 'keywords': {'visible': True, 'enabled': True, 'order': 4, 'label': 'Keywords'}, 'plots': {'visible': True, 'enabled': False, 'order': 9, 'label': 'Plots'}, 'hepdata': {'visible': False, 'enabled': False, 'order': 12, 'label': 'HepData'}, 'holdings': {'visible': [...]

Frame prs_detailed_record in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 5953
-------------------------------------------------------------------------------
      5950         else:
      5951             print_records(req, range(recid, recidb), -1, -9999, of, ot, ln,
      5952                           search_pattern=p, verbose=verbose, tab=tab, sf=sf,
----> 5953                           so=so, sp=sp, rm=rm, em=em, nb_found=len(range(recid, recidb)))
      5954         if req and of.startswith("h"): # register detailed record page view event
      5955             client_ip_address = str(req.remote_ip)
      5956             register_page_view_event(recid, uid, client_ip_address)
-------------------------------------------------------------------------------
                          em =  "''"
                         uid =  '0'
                          cc =  "'Generic'"
                         tab =  "''"
                    keywords =  "'intel, mmx'"
                     verbose =  '0'
                       title =  "'MMX'"
                          ln =  "'en'"
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                      kwargs =  "{'op1': '', 'op2': '', 'cc': 'Generic', 'd2': '', 'verbose': 0, 'jrec': 0, 'ln': 'en', 'selected_external_collections_infos': None, 'm1': '', 'm3': '', 'm2': '', 'pl': '', 'hosted_colls': [], 'dt': '', 'colls_to_search': ['Generic'], 'p2': '', 'p3': '', 'p1': '', 'f': '', 'p': '', 'recid': 112, 'aas': 0, 'em': '', 'f1': '', 'f2': '', 'f3': '', 'uid': 0, 'datetext2': '', 'datetext1': '', 'ec': [], 'ap': 1, 'tab': '', 'id': -1, 'd2y': 0, 'sysnb': '', 'req': <invenio.legacy.wsgi.SimulatedModPython [...]
                          so =  "'d'"
                 description =  "'Intel MMX instructions\\nIntel'"
                          rm =  "''"
                           _ =  '<function unicode_gettext_wrapper at 0x7f1890791758>'
                       dummy =  "{'f1': '', 'f2': '', 'f3': '', 'op1': '', 'op2': '', 'datetext2': '', 'datetext1': '', 'ec': [], 'ap': 1, 'hosted_colls': [], 'd2': '', 'id': -1, 'd1': '', 'd2y': 0, 'sysnb': '', 'jrec': 0, 'colls_to_display': ['Generic'], 'sysno': '', 'selected_external_collections_infos': None, 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd2d': 0, 'pl': '', 'wash_colls_debug': '', 'wl': 50000, 'sc': 0, 'pl_in_url': '', 'dt': '', 'colls_to_search': ['Generic'], 'p2': '', 'p3': '', 'c': [], 'p1': '', 'f': [...]
                          of =  "'hd'"
                          sp =  "''"
                           p =  "''"
                       recid =  '112'
                         aas =  '0'
                      recidb =  '113'
                          ot =  '[]'
                          sf =  "''"

Frame prs_search in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 5889
-------------------------------------------------------------------------------
      5886     """
      5887     ## 0 - start output
      5888     if recid >= 0: # recid can be 0 if deduced from sysno and if such sysno does not exist
----> 5889         output = prs_detailed_record(kwargs=kwargs, **kwargs)
      5890         if output is not None:
      5891             return output
      5892
-------------------------------------------------------------------------------
                          em =  "''"
                       dummy =  "{'f1': '', 'f2': '', 'f3': '', 'op1': '', 'op2': '', 'datetext2': '', 'datetext1': '', 'ap': 1, 'tab': '', 'd2': '', 'id': -1, 'uid': 0, 'd2y': 0, 'sysnb': '', 'jrec': 0, 'colls_to_display': ['Generic'], 'sysno': '', 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd1': '', 'd2d': 0, 'pl': '', 'hosted_colls': [], 'wl': 50000, 'pl_in_url': '', 'dt': '', 'colls_to_search': ['Generic'], '_': <function unicode_gettext_wrapper at 0x7f1890791758>, 'wash_colls_debug': '', 'c': [], 'sp': '', 'd1y': 0 [...]
                          p1 =  "''"
                           p =  "''"
                     verbose =  '0'
                           f =  "''"
        selected_external_collections_infos =  'None'
                          of =  "'hb'"
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                          ec =  '[]'
                          p3 =  "''"
                          ln =  "'en'"
                          p2 =  "''"
                       recid =  '112'
                      kwargs =  "{'op1': '', 'op2': '', 'cc': 'Generic', 'd2': '', 'verbose': 0, 'jrec': 0, 'ln': 'en', 'selected_external_collections_infos': None, 'm1': '', 'm3': '', 'm2': '', 'pl': '', 'hosted_colls': [], 'dt': '', 'colls_to_search': ['Generic'], 'p2': '', 'p3': '', 'p1': '', 'f': '', 'p': '', 'recid': 112, 'aas': 0, 'em': '', 'f1': '', 'f2': '', 'f3': '', 'uid': 0, 'datetext2': '', 'datetext1': '', 'ec': [], 'ap': 1, 'tab': '', 'id': -1, 'd2y': 0, 'sysnb': '', 'req': <invenio.legacy.wsgi.SimulatedModPython [...]
                      action =  "'search'"
                          rm =  "''"
                          cc =  "'Generic'"

Frame prs_perform_search in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 5729
-------------------------------------------------------------------------------
      5726     out = prs_wash_arguments_colls(kwargs=kwargs, **kwargs)
      5727     if not out:
      5728         return out
----> 5729     return prs_search(kwargs=kwargs, **kwargs)
      5730
      5731
      5732 def prs_wash_arguments_colls(kwargs=None, of=None, req=None, cc=None, c=None, sc=None, verbose=None,
-------------------------------------------------------------------------------
                       dummy =  "{'em': '', 'f1': '', 'f2': '', 'f3': '', 'verbose': 0, 'op2': '', 'cc': 'Generic', 'datetext1': '', 'recid': 112, 'ec': [], 'ap': 1, 'tab': '', 'uid': 0, 'd2': '', 'id': -1, 'op1': '', 'd2y': 0, 'sysnb': '', 'jrec': 0, 'ln': 'en', 'req': <invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>, 'sysno': '', 'datetext2': '', 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd1': '', 'd2d': 0, 'pl': '', 'wl': 50000, 'selected_external_collections_infos': None, 'sc': 0, 'rm': '',  [...]
                      kwargs =  "{'op1': '', 'op2': '', 'cc': 'Generic', 'd2': '', 'verbose': 0, 'jrec': 0, 'ln': 'en', 'selected_external_collections_infos': None, 'm1': '', 'm3': '', 'm2': '', 'pl': '', 'hosted_colls': [], 'dt': '', 'colls_to_search': ['Generic'], 'p2': '', 'p3': '', 'p1': '', 'f': '', 'p': '', 'recid': 112, 'aas': 0, 'em': '', 'f1': '', 'f2': '', 'f3': '', 'uid': 0, 'datetext2': '', 'datetext1': '', 'ec': [], 'ap': 1, 'tab': '', 'id': -1, 'd2y': 0, 'sysnb': '', 'req': <invenio.legacy.wsgi.SimulatedModPython [...]
                         out =  'True'

Frame perform_request_search in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 5718
-------------------------------------------------------------------------------
      5715                                 d1y=d1y, d1m=d1m, d1d=d1d, d2=d2, d2y=d2y, d2m=d2m, d2d=d2d, dt=dt, verbose=verbose, ap=ap, ln=ln, ec=ec,
      5716                                 tab=tab, wl=wl, em=em)
      5717
----> 5718     return prs_perform_search(kwargs=kwargs, **kwargs)
      5719
      5720
      5721 def prs_perform_search(kwargs=None, **dummy):
-------------------------------------------------------------------------------
                          em =  "''"
                          m2 =  "''"
                          f2 =  "''"
                          f3 =  "''"
                     verbose =  '0'
                         op2 =  "''"
                          f1 =  "''"
                          cc =  "u'B2Share'"
                          ec =  '[]'
                          ap =  '1'
                         tab =  "''"
                          d2 =  "''"
                          id =  '-1'
                          d1 =  "''"
                         d2y =  '0'
                       sysnb =  "''"
                        jrec =  '0'
                          ln =  "'en'"
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                       sysno =  "''"
                          rg =  '10'
                         d2m =  '0'
                          m3 =  "''"
                      kwargs =  "{'op1': '', 'op2': '', 'cc': 'Generic', 'd2': '', 'verbose': 0, 'jrec': 0, 'ln': 'en', 'selected_external_collections_infos': None, 'm1': '', 'm3': '', 'm2': '', 'pl': '', 'hosted_colls': [], 'dt': '', 'colls_to_search': ['Generic'], 'p2': '', 'p3': '', 'p1': '', 'f': '', 'p': '', 'recid': 112, 'aas': 0, 'em': '', 'f1': '', 'f2': '', 'f3': '', 'uid': 0, 'datetext2': '', 'datetext1': '', 'ec': [], 'ap': 1, 'tab': '', 'id': -1, 'd2y': 0, 'sysnb': '', 'req': <invenio.legacy.wsgi.SimulatedModPython [...]
                          m1 =  "''"
                         d2d =  '0'
                          wl =  '50000'
                         op1 =  "''"
                          sc =  '0'
                          rm =  "''"
                          dt =  "''"
                          p2 =  "''"
                          p3 =  "''"
                           c =  '[]'
                          p1 =  "''"
                          so =  "'d'"
                           f =  "''"
                          of =  "'hb'"
                          sp =  "''"
                         d1y =  '0'
                         d1d =  '0'
                           p =  "''"
                       recid =  '112'
                         aas =  '0'
                      recidb =  '-1'
                      action =  "'search'"
                         d1m =  '0'
                          ot =  '[]'
                         idb =  '-1'
                          sf =  "''"

Frame __call__ in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/websearch/webinterface.py at line 1184
                    auth_msg =  "''"
                         uid =  '0'
                        form =  '{}'
                        self =  '<invenio.legacy.websearch.webinterface.WebInterfaceRecordExport object at 0x7f18902d5710>'
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                   user_info =  "UserInfo([{'referer': None, 'remote_host': '', 'uri': '/record/112/export', 'agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36', 'remote_ip': '194.136.154.133'}, <CallbackDict {'settings': {}, 'uid': 0, 'id': 0}>, {}, {'precached_usestats': False, 'precached_usemessages': False, 'uid': -1, 'agent': '', 'uri': '', 'precached_usegroups': False, 'session': None, 'referer': '', 'precached_canseehiddenmarctags': False, 'precached_u [...]
                   auth_code =  '0'
                        argd =  "{'em': '', 'f1': '', 'f2': '', 'f3': '', 'op1': '', 'op2': '', 'cc': u'B2Share', 'ec': [], 'ap': 1, 'd2': '', 'id': -1, 'd1': '', 'd2y': 0, 'sysnb': '', 'jrec': 0, 'ln': 'en', 'sysno': '', 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd2d': 0, 'wl': 50000, 'action': 'search', 'rm': '', 'verbose': 0, 'dt': '', 'p2': '', 'p3': '', 'c': [], 'p1': '', 'so': 'd', 'f': '', 'of': 'hb', 'sp': '', 'd1y': 0, 'd1d': 0, 'p': '', 'recid': 112, 'aas': 0, 'recidb': -1, 'sc': 0, 'd1m': 0, 'ot': [], 'idb': [...]

Frame _traverse in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/handler.py at line 252
-------------------------------------------------------------------------------
       249         warnings.warn("Accessed deprecated page {0.uri}".format(req),
       250                       PendingDeprecationWarning, stacklevel=2)
       251         form = req.form
---->  252         result = _check_result(req, obj(req, form))
       253         return result
       254
       255     def __call__(self, req, form):
-------------------------------------------------------------------------------
                         obj =  '<invenio.legacy.websearch.webinterface.WebInterfaceRecordExport object at 0x7f18902d5710>'
                        name =  "'export'"
                        form =  '{}'
                     guest_p =  '1'
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                   component =  "'export'"
                     do_head =  'False'
                        path =  '[]'
                        self =  '<invenio.legacy.websearch.webinterface.WebInterfaceRecordPages object at 0x7f18905d7e10>'

Frame _traverse in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/handler.py at line 241
-------------------------------------------------------------------------------
       238         # renderer. We even pass it the parsed form arguments.
       239         if path:
       240             if hasattr(obj, '_traverse'):
---->  241                 return obj._traverse(req, path, do_head, guest_p)
       242             else:
       243                 raise apache.SERVER_RETURN, apache.HTTP_NOT_FOUND
       244
-------------------------------------------------------------------------------
                         obj =  '<invenio.legacy.websearch.webinterface.WebInterfaceRecordPages object at 0x7f18905d7e10>'
                        name =  'None'
                     guest_p =  '1'
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                   component =  "'record'"
                     do_head =  'False'
                        path =  "['export']"
                        self =  '<invenio.ext.legacy.layout.WebInterfaceInvenio object at 0x7f189ad86590>'

Frame _handler in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/handler.py at line 358
-------------------------------------------------------------------------------
       355                     args = cgi.parse_qs(req.args)
       356                     if 'debug' in args:
       357                         remote_debugger.error_msg(args['debug'])
---->  358             register_exception(req=req, alert_admin=True)
       359             raise
       360
       361         # Serve an error by default.
-------------------------------------------------------------------------------
             allowed_methods =  "('GET', 'POST', 'HEAD', 'OPTIONS', 'PUT')"
                           g =  'None'
                     guest_p =  '1'
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18905d77d0>'
                         uri =  "'/record/112/export'"
                        path =  "['record', '112', 'export']"
                        root =  '<invenio.ext.legacy.layout.WebInterfaceInvenio object at 0x7f189ad86590>'
                    bad_msie =  'None'
```

**Comment by llehtine** [comment]
This is generated when trying to access the export-link without giving any parameter, for example: https://b2share.eudat.eu/record/6/export

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
