### ISSUE TITLE
engine.py creates error message

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#685]
```
ello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 12:45:05
    last time it was notified: 2015-06-16 12:45:05

An error occured while formatting record 6 in web-inf/web.xml?
* 2015-06-16 12:45:05 -> InvenioBibFormatError: Could not find output format named WEBINFWEBXML.BFO. (engine.py:1855:resolve_output_format_filename)

** User details
No client information available

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py", line 504, in format_record_1st_pass
    **kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py", line 350, in format_record
    template = decide_format_template(bfo, of)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py", line 582, in decide_format_template
    output_format = get_output_format(of)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py", line 1626, in get_output_format
    filename = resolve_output_format_filename(code, verbose)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py", line 1855, in resolve_output_format_filename
    raise InvenioBibFormatError(_('Could not find output format named %(x_code)s.', x_code=code))
InvenioBibFormatError: Could not find output format named WEBINFWEBXML.BFO.

** Stack frame details

Frame resolve_output_format_filename in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py at line 1855
-------------------------------------------------------------------------------
      1852             return filename
      1853
      1854     # No output format with that name found
----> 1855     raise InvenioBibFormatError(_('Could not find output format named %(x_code)s.', x_code=code))
      1856
      1857     if verbose >= 5:
      1858         sys.stderr.write(exc.message)
-------------------------------------------------------------------------------
                        code =  "u'WEBINFWEBXML.BFO'"
                     verbose =  '0'
                           _ =  '<function unicode_gettext_wrapper at 0x7f1891371488>'
                    filename =  "'XO.bfo'"

Frame get_output_format in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py at line 1626
-------------------------------------------------------------------------------
      1623     """
      1624     _ = gettext_set_language(CFG_SITE_LANG)
      1625     output_format = {'rules': [], 'default': ""}
----> 1626     filename = resolve_output_format_filename(code, verbose)
      1627
      1628     if filename is None:
      1629         try:
-------------------------------------------------------------------------------
                        code =  "u'web-inf/web.xml?'"
               output_format =  "{'rules': [], 'default': ''}"
             with_attributes =  'False'
                     verbose =  '0'
                           _ =  '<function unicode_gettext_wrapper at 0x7f1891371aa0>'

Frame decide_format_template in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py at line 582
-------------------------------------------------------------------------------
       579     @return: name of a format template
       580     """
       581
---->  582     output_format = get_output_format(of)
       583
       584     for rule in output_format['rules']:
       585         if rule['field'].startswith('00'):
-------------------------------------------------------------------------------
                          of =  "u'web-inf/web.xml?'"
                         bfo =  '<invenio.modules.formatter.engine.BibFormatObject object at 0x7f1891495390>'

Frame format_record in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py at line 350
-------------------------------------------------------------------------------
       347         return "", False
       348
       349     #Find out which format template to use based on record and output format.
---->  350     template = decide_format_template(bfo, of)
       351     if verbose == 9 and template is not None:
       352         out += """\n<br/><span class="quicknote">
       353         Using %s template for record %i.
-------------------------------------------------------------------------------
                     verbose =  '0'
                  xml_record =  'None'
                          ln =  "'en'"
                         qid =  "''"
                          of =  "u'web-inf/web.xml?'"
                         bfo =  '<invenio.modules.formatter.engine.BibFormatObject object at 0x7f1891495390>'
                   user_info =  'None'
                       recID =  '6'
                      kwargs =  "{'extra_context': {'collection': Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 113>}}"
              search_pattern =  '[]'
                           _ =  '<function unicode_gettext_wrapper at 0x7f1891371140>'
                         out =  "''"

Frame format_record_1st_pass in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/engine.py at line 524
-------------------------------------------------------------------------------
       521     except Exception, e:
       522         register_exception(prefix="An error occured while formatting record %s in %s" %
       523                            (recID, of),
---->  524                            alert_admin=True)
       525         #Failsafe execution mode
       526         import invenio.legacy.template
       527         websearch_templates = invenio.legacy.template.load('websearch')
-------------------------------------------------------------------------------
                           e =  'InvenioBibFormatError()'
                     verbose =  '0'
                  xml_record =  'None'
                          ln =  "'en'"
                         res =  'None'
                  on_the_fly =  'False'
                   user_info =  'None'
                save_missing =  'True'
                          of =  "u'web-inf/web.xml?'"
                       recID =  '6'
                      kwargs =  "{'extra_context': {'collection': Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 113>}}"
              search_pattern =  '[]'
               record_exists =  '<function record_exists at 0x7f1898534b18>'
              needs_2nd_pass =  'None'
                         out =  "''"
```

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
