### ISSUE TITLE
x.tpl generates error message

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#687]
```
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 12:43:25
    last time it was notified: 2015-06-16 12:43:25

* 2015-06-16 12:43:25 -> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 161: ordinal not in range(128) (x.tpl:21:top-level template code)

** User details
                                     agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
                                     email:
                               family_name:
                               given_names:
                                     group: []
                                     guest: 1
                                        id: 0
                                  nickname:
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: False
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <https://trng-eudatis.csc.fi/>
                               remote_host:
                                 remote_ip: 194.136.154.133
                                   session: None
                                  settings: {}
                                       uid: 0
                                       uri: </search>

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py", line 258, in error_router
    return original_handler(e)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py", line 203, in decorator
    return f(*args, **argd)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py", line 149, in decorated
    return method(collection, *args, **kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py", line 472, in search
    return response_formated_records(recids, collection, of, **ctx)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py", line 158, in response_formated_records
    of=of, **kwargs))
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/__init__.py", line 468, in print_records
    **context)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/template/__init__.py", line 56, in render_template_to_string
    return template.render(context)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/templates/format/records/x.tpl", line 21, in top-level template code
    {{ format_record(recid, of=of) }}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 161: ordinal not in range(128)

** Stack frame details

Frame top-level template code in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/templates/format/records/x.tpl at line 21
        tfn_get_fulltext_snippets =  '<function template_context_function at 0x7f189b6b3668>'
                     verbose =  '0'
               format_record =  '<function format_record at 0x7f18bfed5b90>'
        tfn_get_fieldvalues_alephseq_like =  '<function template_context_function at 0x7f189b68e1b8>'
                         qid =  "'f200a1942011235957ab306fad0ec125'"
                      lipsum =  '<function generate_lorem_ipsum at 0x7f18be10ae60>'
                  get_record =  "<bound method StorageEngine.get_record of <class 'invenio.modules.records.api.Record'>>"
                     session =  '<Session {\'websearch-last-query\': "/search?action_search=&ln=en&of=xkeZxEmZ\');%20waitfor%20delay%20\'0:0:6\'%20--%20&p=1&so=a", \'_id\': \'400b0d493e960d285a88a68202d149e7\', \'websearch-last-query-hits\': [1, 6, 15, 16, 23, 25, 26, 43, 55, 88]}>'
        get_flashed_messages =  '<function get_flashed_messages at 0x7f18be2faed8>'
        tfn_summarize_records =  '<function template_context_function at 0x7f189b68e2a8>'
               canonical_url =  "u'https://trng-b2share.eudat.eu/search'"
                        jrec =  '1'
            easy_search_form =  '<invenio.modules.search.forms.EasySearchForm object at 0x7f1891e32510>'
                          ln =  "u'en'"
                 breadcrumbs =  '[<flask_menu.MenuEntryMixin object at 0x7f189a8044d0>, <flask_menu.MenuEntryMixin object at 0x7f189a80a7d0>]'
                current_menu =  '<flask_menu.MenuEntryMixin object at 0x7f18c4a93310>'
                     gettext =  '<function gettext at 0x7f18be80e410>'
        create_nearest_terms_box =  '<function <lambda> at 0x7f1890786320>'
                          rg =  '10'
                        dict =  '<function <lambda> at 0x7f18be181c80>'
                current_user =  "UserInfo([{'referer': 'https://trng-eudatis.csc.fi/', 'remote_host': '', 'uri': '/search', 'agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36', 'remote_ip': '194.136.154.133'}, <CallbackDict {'settings': {}, 'uid': 0, 'id': 0}>, {}, {'precached_usestats': False, 'precached_usemessages': False, 'uid': -1, 'agent': '', 'uri': '', 'precached_usegroups': False, 'session': None, 'referer': '', 'precached_canseehiddenmarctags': Fals [...]
             is_language_rtl =  '<function is_language_rtl at 0x7f18bfb7c9b0>'
                      config =  "ERROR: when representing the value: unknown locale 'e'"
              alternate_urls =  "{u'e': u'https://trng-b2share.eudat.eu/search?ln=e', u'n': u'https://trng-b2share.eudat.eu/search?ln=n'}"
                  collection =  'Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 113>'
                    ngettext =  '<function ngettext at 0x7f18be80e488>'
                     records =  '10'
                           _ =  '<function _gettext_alias at 0x7f18be6a8758>'
                  pagination =  '<invenio.utils.pagination.Pagination object at 0x7f1891e32490>'
        tfn_webtag_record_tags =  '<function template_context_function at 0x7f189b6aac80>'
                     url_for =  '<function invenio_url_for at 0x7f189081d668>'
                           g =  "<flask.g of 'invenio.base'>"
                      recids =  '[1, 6, 15, 16, 23, 25, 26, 43, 55, 88]'
        tfn_get_back_to_search_links =  '<function template_context_function at 0x7f189b6b30c8>'
                          of =  'u"xkezxemz\'); waitfor delay \'0:0:6\' -- "'
                      facets =  '[]'
                     request =  "<LegacyRequest 'https://trng-eudatis.csc.fi/search?action_search=&ln=en&of=xkeZxEmZ')%3B waitfor delay '0:0:6' -- &p=1&so=a' [GET]>"
                  get_bundle =  '<function get_bundle at 0x7f189b2990c8>'
                       range =  "<type 'xrange'>"
                      joiner =  "<class 'jinja2.utils.Joiner'>"
                       recid =  '1'
                        time =  "<module 'time' from '/var/www/.virtualenvs/b2share/lib/python2.7/lib-dynload/time.so'>"
              export_formats =  '[<invenio.modules.formatter.models.Format object at 0x7f189bd3fcd0>, <invenio.modules.formatter.models.Format object at 0x7f189bd3f610>, <invenio.modules.formatter.models.Format object at 0x7f189bd3fc10>, <invenio.modules.formatter.models.Format object at 0x7f189bd3f350>, <invenio.modules.formatter.models.Format object at 0x7f189bd3fdd0>, <invenio.modules.formatter.models.Format object at 0x7f1890815790>, <invenio.modules.formatter.models.Format object at 0x7f1890815650>]'
                      cycler =  "<class 'jinja2.utils.Cycler'>"
                          ot =  'None'

Frame handle_exception in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py at line 742
-------------------------------------------------------------------------------
       739         if self.exception_handler is not None:
       740             self.exception_handler(traceback)
       741         exc_type, exc_value, tb = traceback.standard_exc_info
---->  742         reraise(exc_type, exc_value, tb)
       743
       744     def join_path(self, template, parent):
       745         """Join a template with the parent.  By default all the lookups are
-------------------------------------------------------------------------------
                 source_hint =  'None'
                    rendered =  'True'
                        self =  '<flask.templating.Environment object at 0x7f18be80d390>'
                   traceback =  '<jinja2.debug.ProcessedTraceback object at 0x7f1891e22050>'
                    exc_type =  "<type 'exceptions.UnicodeDecodeError'>"
                    exc_info =  '(<type \'exceptions.UnicodeDecodeError\'>, UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/ [...]
                          tb =  '<traceback object at 0x7f18901098c0>'
                   exc_value =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]

Frame render in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/jinja2/environment.py at line 969
                    exc_info =  '(<type \'exceptions.UnicodeDecodeError\'>, UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/ [...]
                        self =  "<Template u'format/records/x.tpl'>"
                        args =  '({\'tfn_get_fulltext_snippets\': <function template_context_function at 0x7f189b6b3668>, \'verbose\': 0, \'format_record\': <function format_record at 0x7f18bfed5b90>, \'tfn_get_fieldvalues_alephseq_like\': <function template_context_function at 0x7f189b68e1b8>, \'qid\': \'f200a1942011235957ab306fad0ec125\', \'get_record\': <bound method StorageEngine.get_record of <class \'invenio.modules.records.api.Record\'>>, \'session\': <Session {\'websearch-last-query\': "/search?action_search=&ln=en&of= [...]
                        vars =  '{\'tfn_get_fulltext_snippets\': <function template_context_function at 0x7f189b6b3668>, \'verbose\': 0, \'format_record\': <function format_record at 0x7f18bfed5b90>, \'tfn_get_fieldvalues_alephseq_like\': <function template_context_function at 0x7f189b68e1b8>, \'qid\': \'f200a1942011235957ab306fad0ec125\', \'get_record\': <bound method StorageEngine.get_record of <class \'invenio.modules.records.api.Record\'>>, \'session\': <Session {\'websearch-last-query\': "/search?action_search=&ln=en&of=x [...]
                      kwargs =  '{}'

Frame render_template_to_string in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/template/__init__.py at line 56
                _from_string =  'False'
                         ctx =  "<RequestContext 'https://trng-eudatis.csc.fi/search?action_search=&ln=en&of=xkeZxEmZ')%3B waitfor delay '0:0:6' -- &p=1&so=a' [GET] of invenio.base>"
                     context =  '{\'tfn_get_fulltext_snippets\': <function template_context_function at 0x7f189b6b3668>, \'verbose\': 0, \'format_record\': <function format_record at 0x7f18bfed5b90>, \'tfn_get_fieldvalues_alephseq_like\': <function template_context_function at 0x7f189b68e1b8>, \'qid\': \'f200a1942011235957ab306fad0ec125\', \'get_record\': <bound method StorageEngine.get_record of <class \'invenio.modules.records.api.Record\'>>, \'session\': <Session {\'websearch-last-query\': "/search?action_search=&ln=en&of=x [...]
                    template =  "<Template u'format/records/x.tpl'>"
                       input =  '[u"format/records/xkezxemz\'); waitfor delay \'0:0:6\' -- .tpl", u\'format/records/x.tpl\', \'format/records/text_html.tpl\']'

Frame print_records in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/formatter/__init__.py at line 468
-------------------------------------------------------------------------------
       465          'format/records/%s.tpl' % of[0],
       466          'format/records/%s.tpl' % get_output_format_content_type(of).
       467             replace('/', '_')],
---->  468         **context)
       469
       470
       471 def usage(exitcode=1, msg=""):
-------------------------------------------------------------------------------
                  Pagination =  "<class 'invenio.utils.pagination.Pagination'>"
               wash_language =  '<function wash_language at 0x7f18bfb7c848>'
                        jrec =  '1'
                  on_the_fly =  'False'
                      recIDs =  '[1, 6, 15, 16, 23, 25, 26, 43, 55, 88]'
        TEMPLATE_CONTEXT_FUNCTIONS_CACHE =  '<invenio.modules.formatter.engine.LazyTemplateContextFunctionsCache object at 0x7f189a5a7e90>'
                          ln =  "u'en'"
                         ctx =  "{'easy_search_form': <invenio.modules.search.forms.EasySearchForm object at 0x7f1891e32510>, 'records': 10, 'qid': 'f200a1942011235957ab306fad0ec125', 'facets': [], 'collection': Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 113>, 'create_nearest_terms_box': <function <lambda> [...]
                      Format =  "<class 'invenio.modules.formatter.models.Format'>"
                     request =  "<LegacyRequest 'https://trng-eudatis.csc.fi/search?action_search=&ln=en&of=xkeZxEmZ')%3B waitfor delay '0:0:6' -- &p=1&so=a' [GET]>"
                        ceil =  '<built-in function ceil>'
              search_pattern =  "''"
                     records =  '10'
                          rg =  '10'
                     context =  '{\'tfn_get_fulltext_snippets\': <function template_context_function at 0x7f189b6b3668>, \'verbose\': 0, \'format_record\': <function format_record at 0x7f18bfed5b90>, \'tfn_get_fieldvalues_alephseq_like\': <function template_context_function at 0x7f189b68e1b8>, \'qid\': \'f200a1942011235957ab306fad0ec125\', \'collection\': Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbr [...]
                        time =  "<module 'time' from '/var/www/.virtualenvs/b2share/lib/python2.7/lib-dynload/time.so'>"
        render_template_to_string =  '<function render_template_to_string at 0x7f18bfa4b410>'
                          of =  'u"xkezxemz\'); waitfor delay \'0:0:6\' -- "'
                          ot =  "['']"
                       pages =  '1'
                     verbose =  '0'

Frame response_formated_records in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py at line 158
-------------------------------------------------------------------------------
       155     from invenio.modules.formatter import (get_output_format_content_type,
       156                                            print_records)
       157     response = make_response(print_records(recids, collection=collection,
---->  158                                            of=of, **kwargs))
       159     response.mimetype = get_output_format_content_type(of)
       160     return response
       161
-------------------------------------------------------------------------------
        get_output_format_content_type =  '<function get_output_format_content_type at 0x7f18bfed5de8>'
                      recids =  '[1, 6, 15, 16, 23, 25, 26, 43, 55, 88]'
                          of =  'u"xkeZxEmZ\'); waitfor delay \'0:0:6\' -- "'
                  collection =  'Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 113>'
               print_records =  '<function print_records at 0x7f18bfed5e60>'
                      kwargs =  "{'easy_search_form': <invenio.modules.search.forms.EasySearchForm object at 0x7f1891e32510>, 'create_nearest_terms_box': <function <lambda> at 0x7f1890786320>, 'qid': 'f200a1942011235957ab306fad0ec125', 'facets': [], 'records': 10, 'rg': 10, 'ot': None}"

Frame search in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py at line 472
-------------------------------------------------------------------------------
       469         ot=ot
       470     )
       471
---->  472     return response_formated_records(recids, collection, of, **ctx)
       473
       474
       475 @blueprint.route('/facet/<name>/<qid>', methods=['GET', 'POST'])
-------------------------------------------------------------------------------
                   argd_orig =  "{'em': '', 'f1': '', 'f2': '', 'f3': '', 'op1': '', 'op2': '', 'cc': u'B2Share', 'ec': [], 'ap': 1, 'd2': '', 'id': -1, 'd1': '', 'd2y': 0, 'sysnb': '', 'jrec': 0, 'ln': 'en', 'sysno': '', 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd2d': 0, 'wl': 50000, 'action': 'search', 'rm': '', 'verbose': 0, 'dt': '', 'p2': '', 'p3': '', 'c': [], 'p1': '', 'so': 'a', 'f': '', 'of': 'id', 'sp': '', 'd1y': 0, 'd1d': 0, 'p': '1', 'recid': -1, 'aas': 0, 'recidb': -1, 'sc': 0, 'd1m': 0, 'ot': [], 'idb': [...]
        perform_request_search =  '<function perform_request_search at 0x7f1898c31d70>'
                      recids =  '[1, 6, 15, 16, 23, 25, 26, 43, 55, 88]'
                         qid =  "'f200a1942011235957ab306fad0ec125'"
                         ctx =  "{'records': 10, 'rg': 10, 'easy_search_form': <invenio.modules.search.forms.EasySearchForm object at 0x7f1891e32510>, 'create_nearest_terms_box': <function <lambda> at 0x7f1890786320>, 'qid': 'f200a1942011235957ab306fad0ec125', 'facets': [], 'ot': None}"
             last_query_hits =  '[1, 6, 15, 16, 23, 25, 26, 43, 55, 88]'
                  collection =  'Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 113>'
                           p =  "u'1'"
                          rg =  '10'
                          so =  "u'a'"
                   hit_limit =  '1000'
                          of =  'u"xkeZxEmZ\'); waitfor delay \'0:0:6\' -- "'
                          rm =  'None'
                          ot =  'None'
                        argd =  "{'em': '', 'f1': '', 'f2': '', 'f3': '', 'op1': '', 'op2': '', 'cc': u'B2Share', 'ec': [], 'ap': 1, 'd2': '', 'id': -1, 'd1': '', 'd2y': 0, 'sysnb': '', 'jrec': 0, 'ln': 'en', 'sysno': '', 'rg': 10, 'm1': '', 'm3': '', 'm2': '', 'd2m': 0, 'd2d': 0, 'wl': 50000, 'action': 'search', 'rm': '', 'verbose': 0, 'dt': '', 'p2': '', 'p3': '', 'c': [], 'p1': '', 'so': 'a', 'f': '', 'of': 'id', 'sp': '', 'd1y': 0, 'd1d': 0, 'p': '1', 'recid': -1, 'aas': 0, 'recidb': -1, 'sc': 0, 'd1m': 0, 'ot': [], 'idb': [...]

Frame decorated in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/search/views/search.py at line 149
-------------------------------------------------------------------------------
       146             elif auth_code:
       147                 return abort(401)
       148
---->  149         return method(collection, *args, **kwargs)
       150     return decorated
       151
       152
-------------------------------------------------------------------------------
                        name =  'None'
                        args =  '()'
                  collection =  'Collection <id: 1, name: B2Share, dbquery: SELECT collection.id AS collection_id, collection.name AS collection_name, collection.dbquery AS collection_dbquery, collection.nbrecs AS collection_nbrecs, collection.reclist AS collection_reclist \nFROM collection, nbrecs: 113>'
                 name_getter =  '<function collection_name_from_request at 0x7f18c5850a28>'
                      kwargs =  '{\'p\': u\'1\', \'ot\': None, \'so\': u\'a\', \'rm\': None, \'of\': u"xkeZxEmZ\'); waitfor delay \'0:0:6\' -- "}'
          default_collection =  'True'
                      method =  '<function search at 0x7f18c58550c8>'
                         uid =  '0'

Frame decorator in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py at line 203
-------------------------------------------------------------------------------
       200             from invenio.utils.washers import wash_urlargd
       201             argd = wash_urlargd(request.values, config)
       202             argd.update(kwargs)
---->  203             return f(*args, **argd)
       204         return decorator
       205     return _decorated
-------------------------------------------------------------------------------
                           f =  '<function search at 0x7f18c5855140>'
                        argd =  '{\'p\': u\'1\', \'of\': u"xkeZxEmZ\'); waitfor delay \'0:0:6\' -- ", \'ot\': None, \'so\': u\'a\', \'rm\': None}'
                        args =  '()'
                      kwargs =  '{}'
                wash_urlargd =  '<function wash_urlargd at 0x7f189b480de8>'
                      config =  "{'p': (<type 'unicode'>, ''), 'ot': (<type 'unicode'>, None), 'so': (<type 'unicode'>, None), 'rm': (<type 'unicode'>, None), 'of': (<type 'unicode'>, u'hb')}"

Frame dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1461
-------------------------------------------------------------------------------
      1458            and req.method == 'OPTIONS':
      1459             return self.make_default_options_response()
      1460         # otherwise dispatch to the handler for that endpoint
----> 1461         return self.view_functions[rule.endpoint](**req.view_args)
      1462
      1463     def full_dispatch_request(self):
      1464         """Dispatches the request and on top of that performs request
-------------------------------------------------------------------------------
                        self =  "<Flask 'invenio.base'>"
                         req =  "<LegacyRequest 'https://trng-eudatis.csc.fi/search?action_search=&ln=en&of=xkeZxEmZ')%3B waitfor delay '0:0:6' -- &p=1&so=a' [GET]>"
                        rule =  "<Rule '/search' (HEAD, POST, OPTIONS, GET) -> search.search>"

Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477
-------------------------------------------------------------------------------
      1474             if rv is None:
      1475                 rv = self.dispatch_request()
      1476         except Exception as e:
----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
      1480         request_finished.send(self, response=response)
-------------------------------------------------------------------------------
                          rv =  'None'
                           e =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]
                        self =  "<Flask 'invenio.base'>"

Frame handle_user_exception in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1381
-------------------------------------------------------------------------------
      1378             if isinstance(e, typecheck):
      1379                 return handler(e)
      1380
----> 1381         reraise(exc_type, exc_value, tb)
      1382
      1383     def handle_exception(self, e):
      1384         """Default exception handling that kicks in when an exception
-------------------------------------------------------------------------------
                           e =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]
                    handlers =  'None'
                        self =  "<Flask 'invenio.base'>"
                   exc_value =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]
          blueprint_handlers =  '()'
                app_handlers =  '()'
                          tb =  '<traceback object at 0x7f18901e81b8>'
                    exc_type =  "<type 'exceptions.UnicodeDecodeError'>"

Frame handle_user_exception in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py at line 125
-------------------------------------------------------------------------------
       122         Hook a before handle to it.
       123         """
       124         before_handle_user_exception.send(e)
---->  125         return super(Flask, self).handle_user_exception(e)
       126
       127
       128 def lazy_import(name):
-------------------------------------------------------------------------------
                        self =  "<Flask 'invenio.base'>"
                           e =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]

Frame error_router in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/__init__.py at line 258
-------------------------------------------------------------------------------
       255         """
       256         if self._has_fr_route():
       257             return self.handle_error(e)
---->  258         return original_handler(e)
       259
       260     def handle_error(self, e):
       261         """Error handler for the API transforms a raised exception into a Flask
-------------------------------------------------------------------------------
            original_handler =  "<bound method Flask.handle_user_exception of <Flask 'invenio.base'>>"
                        self =  '<flask_restful.Api object at 0x7f18c450f9d0>'
                           e =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]

Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477
-------------------------------------------------------------------------------
      1474             if rv is None:
      1475                 rv = self.dispatch_request()
      1476         except Exception as e:
----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
      1480         request_finished.send(self, response=response)
-------------------------------------------------------------------------------
                          rv =  'None'
                           e =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]
                        self =  "<Flask 'invenio.base'>"

Frame __call__ in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py at line 127
-------------------------------------------------------------------------------
       124                     response = self.app.full_dispatch_request()
       125                 except Exception as e:
       126                     from invenio.ext.logging import register_exception
---->  127                     register_exception(req=request, alert_admin=True)
       128                     response = self.app.handle_exception(e)
       129
       130                 return response(environ, start_response)
-------------------------------------------------------------------------------
              start_response =  '<built-in method start_response of mod_wsgi.Adapter object at 0x7f189081d918>'
                     environ =  '{\'wsgi.version\': (1, 0), \'mod_wsgi.listener_port\': \'443\', \'HTTP_REFERER\': \'https://trng-eudatis.csc.fi/\', \'SERVER_SOFTWARE\': \'Apache\', \'SCRIPT_NAME\': \'\', \'mod_wsgi.enable_sendfile\': \'0\', \'mod_wsgi.handler_script\': \'\', \'SERVER_SIGNATURE\': \'\', \'REQUEST_METHOD\': \'GET\', \'PATH_INFO\': \'/search\', \'SERVER_PROTOCOL\': \'HTTP/1.1\', \'QUERY_STRING\': "action_search=&ln=en&of=xkeZxEmZ\');%20waitfor%20delay%20\'0:0:6\'%20--%20&p=1&so=a", \'SSL_TLS_SNI\': \'msp.elatera [...]
                        self =  '<invenio.ext.legacy.LegacyAppMiddleware object at 0x7f18bf7fd750>'
          register_exception =  '<function register_exception at 0x7f18c411b050>'
                           e =  'UnicodeDecodeError(\'ascii\', \'<abbr class="unapi-id" title="1"></abbr>\\n<strong>Prague Dependency Treebank 2.0 Sample Data</strong>  / <a href="/search?ln=en&p=Haji%C4%8D%2C+Jan&f=author">Haji\\xc4\\x8d, Jan</a>  20-01-2014.<br /><small>This is a small sample dataset from PDT 2. [...]</small><br /><small class="note"><a class="note" href="http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-005056943408.zip">http://b2share.eudat.eu/record/1/files/c33a933c-8202-11e3-92a1-00505694340 [...]
```

**Comment by emanueldima** [comment]
We won't use Jinja in b2share2
