### ISSUE TITLE
utf8.py generates error message

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#689]
```
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 12:38:27
    last time it was notified: 2015-06-16 12:38:27

* 2015-06-16 12:38:27 -> UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 8: invalid start byte (utf_8.py:16:decode)

** User details
Error in retrieving contextual information: 'ascii' codec can't decode byte 0xf6 in position 57: ordinal not in range(128)

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/logging/wrappers.py", line 150, in get_pretty_traceback
    client_data = get_pretty_wide_client_info(req)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/logging/wrappers.py", line 57, in get_pretty_wide_client_info
    ret += fmt % (key, "<%s>" % user_info[key])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 57: ordinal not in range(128)

** Stack frame details

Frame get_pretty_wide_client_info in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/logging/wrappers.py at line 57
                        keys =  "['agent', 'email', 'family_name', 'given_names', 'group', 'guest', 'id', 'nickname', 'precached_canseehiddenmarctags', 'precached_permitted_restricted_collections', 'precached_sendcomments', 'precached_useadmin', 'precached_usealerts', 'precached_useapprove', 'precached_usebaskets', 'precached_usegroups', 'precached_useloans', 'precached_usemessages', 'precached_usepaperattribution', 'precached_usepaperclaim', 'precached_usestats', 'precached_viewclaimlink', 'precached_viewsubmissions', 'refere [...]
                     max_key =  '42'
                         fmt =  "'% 42s: %s\\n'"
                         req =  "ERROR: when representing the value: 'ascii' codec can't encode character u'\\ufffd' in position 55: ordinal not in range(128)"
                         ret =  "u'                                     agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36\\n                                     email: \\n                               family_name: \\n                               given_names: \\n                                     group: []\\n                                     guest: 1\\n                                        id: 0\\n                                  nickname: \\n          [...]
                   user_info =  'UserInfo([{\'referer\': \'https://trng-eudatis.csc.fi/\', \'remote_host\': \'\', \'uri\': \'/collection/, {}, {/'precached_usestats/': False, /'precached_usemessages/': False, /'uid/': -1, /'agent/': /'/', /'uri/': /'/', /'precached_usegrou ['>\\xf6" onmouseover=prompt(957694) //\', \'agent\': u\'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36\', \'remote_ip\': \'194.136.154.133\'}, <CallbackDict {\'settings\': {}, \'uid\': 0, \'id\': 0}>, {}, {\'precached_usestats\': False, \'precached_usemessages\': False, \'uid\': -1, \'agent\': \'\', \'uri\': \'\', \'precached_usegrou [...]
           collect_user_info =  '<function collect_user_info at 0x7f18c4da0758>'
                         key =  "'uri'"

Frame get_pretty_traceback in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/logging/wrappers.py at line 170
        traceback_data_stream =  '<StringIO.StringIO instance at 0x7f18907e43b0>'
                         req =  "ERROR: when representing the value: 'ascii' codec can't encode character u'\\ufffd' in position 55: ordinal not in range(128)"
                    exc_name =  "'UnicodeDecodeError'"
                         err =  'UnicodeEncodeError(\'ascii\', u\'<LegacyRequest \\\'https://trng-eudatis.csc.fi/collection/\\ufffd" onmouseover=prompt(957694) ///', 55, 56, /'ordinal not in range(128)/')''>\\\' [GET]>\', 55, 56, \'ordinal not in range(128)\')'
              values_to_hide =  'set([])'
                 skip_frames =  '2'
                       frame =  '<frame object at 0x7f189b7a5b80>'
                     line_no =  '16'
                   exc_value =  '"\'utf8\' codec can\'t decode byte 0xf6 in position 8: invalid start byte"'
                       value =  '"\'uri\'"'
                    filename =  "'utf_8.py'"
                 client_data =  '"Error in retrieving contextual information: \'ascii\' codec can\'t decode byte 0xf6 in position 57: ordinal not in range(128)"'
                         key =  "'key'"
                    exc_info =  '(<type \'exceptions.UnicodeDecodeError\'>, UnicodeDecodeError(\'utf8\', \'<strong>)''>\\xf6" onmouseover=prompt(957694) /</strong>\', 8, 9, \'invalid start byte\'), <traceback object at 0x7f18907e4290>)'
                local_values =  "ERROR: when representing the value: 'ascii' codec can't encode character u'\\ufffd' in position 55: ordinal not in range(128)"
                    www_data =  '"2015-06-16 12:38:27 -> UnicodeDecodeError: \'utf8\' codec can\'t decode byte 0xf6 in position 8: invalid start byte (utf_8.py:16:decode)"'
                       stack =  '[<frame object at 0x7f18905a3c30>, <frame object at 0x7f189b7a5b80>]'
               function_name =  "'decode'"
```

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
