### ISSUE TITLE
connections.py generates error message

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#690]
```
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-06-16 17:03:10
    last time it was notified: 2015-06-16 17:03:10

* 2015-06-16 17:03:09 -> OperationalError: (1139, "Got error 'repetition-operator operand invalid' from regexp") (connections.py:36:defaulterrorhandler)

** User details
                                     agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36
                                     email:
                               family_name:
                               given_names:
                                     group: []
                                     guest: 1
                                        id: 0
                                  nickname:
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: False
                      precached_useapprove: False
                      precached_usebaskets: False
                       precached_usegroups: False
                        precached_useloans: False
                     precached_usemessages: False
             precached_usepaperattribution: False
                   precached_usepaperclaim: False
                        precached_usestats: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <None>
                               remote_host:
                                 remote_ip: 194.136.154.133
                                   session: None
                                  settings: {}
                                       uid: 0
                                       uri: </search>

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 6243, in prs_advanced_search
    results_in_any_collection.union_update(search_pattern_parenthesised(req, p1, f1, m1, ap=ap, of=of, verbose=verbose, ln=ln, wl=wl))
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 2306, in search_pattern_parenthesised
    return search_pattern(req, p, f, m, ap, of, verbose, ln, display_nearest_terms_box=display_nearest_terms_box, wl=wl)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 2209, in search_pattern
    basic_search_unit_hitset = search_pattern(req=None, p=bsu_pn, f=bsu_f, m=bsu_m, of="id", ln=ln, wl=wl)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 2157, in search_pattern
    basic_search_unit_hitset = search_unit(bsu_p, bsu_f, bsu_m, wl)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 2486, in search_unit
    hitset = search_unit_in_idxphrases(p, f, m, wl)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py", line 2780, in search_unit_in_idxphrases
    query_params, wildcard_limit=wl)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py", line 393, in run_sql_with_limit
    res = run_sql(safe_query, param, n, with_desc, run_on_slave=run_on_slave)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py", line 280, in run_sql
    rc = cur.execute(sql, param)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1139, "Got error 'repetition-operator operand invalid' from regexp")

** Stack frame details

Frame defaulterrorhandler in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/connections.py at line 36
-------------------------------------------------------------------------------
        33         connection.messages.append(error)
        34     del cursor
        35     del connection
---->   36     raise errorclass, errorvalue
        37
        38 re_numeric_part = re.compile(r"^(\d+)")
        39
-------------------------------------------------------------------------------
                  errorclass =  "<class '_mysql_exceptions.OperationalError'>"
                  errorvalue =  'OperationalError(1139, "Got error \'repetition-operator operand invalid\' from regexp")'
                       error =  '(<class \'_mysql_exceptions.OperationalError\'>, OperationalError(1139, "Got error \'repetition-operator operand invalid\' from regexp"))'

Frame execute in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/MySQLdb/cursors.py at line 205
-------------------------------------------------------------------------------
       202             exc, value, tb = sys.exc_info()
       203             del tb
       204             self.messages.append((exc, value))
---->  205             self.errorhandler(self, exc, value)
       206         self._executed = query
       207         if not self._defer_warnings: self._warning_check()
       208         return r
-------------------------------------------------------------------------------
                         exc =  "<class '_mysql_exceptions.OperationalError'>"
                        self =  '<MySQLdb.cursors.Cursor object at 0x7f18a2ba9990>'
                        args =  "('*response*write*9915836*9154643*',)"
                          db =  '<weakproxy at 0x7f18a35f7c00 to Connection at 0x7f18a2f9eef0>'
                       value =  'OperationalError(1139, "Got error \'repetition-operator operand invalid\' from regexp")'
                        item =  "'*response*write*9915836*9154643*'"
                           r =  'None'
                       query =  '"SELECT term,hitlist FROM idxPHRASE01F WHERE term REGEXP \'*response*write*9915836*9154643*\' limit 50000"'

Frame run_sql in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py at line 284
-------------------------------------------------------------------------------
       281             gc.enable()
       282         except (OperationalError, InterfaceError):
       283             # unexpected disconnect, bad malloc error, etc
---->  284             raise
       285
       286     if string.upper(string.split(sql)[0]) in \
       287        ("SELECT", "SHOW", "DESC", "DESCRIBE"):
-------------------------------------------------------------------------------
                         cur =  '<MySQLdb.cursors.Cursor object at 0x7f18a2ba9990>'
                   with_desc =  'False'
                      dbhost =  "u'localhost'"
                          db =  "<_mysql.connection open to 'localhost' at 7f18a2f9eef0>"
                       param =  "('*response*write*9915836*9154643*',)"
                           n =  '0'
                  connection =  'None'
                         sql =  "'SELECT term,hitlist FROM idxPHRASE01F WHERE term REGEXP %s limit 50000'"
                   with_dict =  'False'
                run_on_slave =  'False'

Frame run_sql_with_limit in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/dbquery_mysql.py at line 393
-------------------------------------------------------------------------------
       390     if wildcard_limit < 1:  # no limit on the wildcard queries
       391         return run_sql(query, param, n, with_desc, run_on_slave=run_on_slave)
       392     safe_query = query + " limit %s" % wildcard_limit
---->  393     res = run_sql(safe_query, param, n, with_desc, run_on_slave=run_on_slave)
       394     if len(res) == wildcard_limit:
       395         raise InvenioDbQueryWildcardLimitError(res)
       396     return res
-------------------------------------------------------------------------------
                  safe_query =  "'SELECT term,hitlist FROM idxPHRASE01F WHERE term REGEXP %s limit 50000'"
                run_on_slave =  'False'
                   with_desc =  'False'
                       param =  "('*response*write*9915836*9154643*',)"
                           n =  '0'
              wildcard_limit =  '50000'
                       query =  "'SELECT term,hitlist FROM idxPHRASE01F WHERE term REGEXP %s'"

Frame search_unit_in_idxphrases in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 2783
-------------------------------------------------------------------------------
      2780                       query_params, wildcard_limit=wl)
      2781         except InvenioDbQueryWildcardLimitError as excp:
      2782             res = excp.res
----> 2783             limit_reached = 1 # set the limit reached flag to true
      2784     else:
      2785         res = run_sql("SELECT term,hitlist FROM %s WHERE term %s" % (idxphraseX, query_addons), query_params)
      2786     # fill the result set:
-------------------------------------------------------------------------------
                  idxphraseX =  "'idxPHRASE01F'"
                query_params =  "('*response*write*9915836*9154643*',)"
                           f =  "''"
               limit_reached =  '0'
                          wl =  '50000'
                 search_type =  "'r'"
                           p =  "'*response*write*9915836*9154643*'"
                    set_used =  '0'
                      hitset =  'intbitset([])'
             use_query_limit =  'True'
                query_addons =  "'REGEXP %s'"

Frame search_unit in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 2486
-------------------------------------------------------------------------------
      2483                 #for exact match on the admin configured fields we are searching in the pair tables
      2484                 hitset = search_unit_in_idxpairs(p, f, m, wl)
      2485             else:
----> 2486                 hitset = search_unit_in_idxphrases(p, f, m, wl)
      2487         else:
      2488             hitset = search_unit_in_bibxxx(p, f, m, wl)
      2489             # if not hitset and m == 'a' and (p[0] != '%' and p[-1] != '%'):
-------------------------------------------------------------------------------
             ignore_synonyms =  'None'
                   tokenizer =  'None'
                           f =  "''"
                    index_id =  '1'
                          wl =  '50000'
                           m =  "'r'"
                           p =  "'*response*write*9915836*9154643*'"
                      hitset =  'intbitset([])'
             hitset_synonyms =  'intbitset([])'
                  hitset_cjk =  'intbitset([])'

Frame search_pattern in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 2169
-------------------------------------------------------------------------------
      2166         except InvenioWebSearchCitedbyLimitError, excp:
      2167             basic_search_unit_hitset = excp.res
      2168             if of.startswith("h"):
----> 2169                 write_warning(_("Search term after citedby operator too generic, displaying only partial results..."), req=req)
      2170
      2171         # FIXME: print warning if we use native full-text indexing
      2172         if bsu_f == 'fulltext' and bsu_m != 'w' and of.startswith('h') and not CFG_SOLR_URL:
-------------------------------------------------------------------------------
                       bsu_f =  "''"
                    idx_unit =  '0'
              can_see_hidden =  'False'
                           p =  "'*response*write*9915836*9154643*'"
          basic_search_units =  "[['+', '*response*write*9915836*9154643*', '', 'r']]"
                           f =  "''"
                          ln =  "'en'"
                       bsu_o =  "'+'"
                       bsu_m =  "'r'"
                           m =  "'r'"
                          wl =  '50000'
        basic_search_units_hitsets =  '[]'
                         req =  'None'
                          ap =  '0'
        display_nearest_terms_box =  'True'
                       bsu_p =  "'*response*write*9915836*9154643*'"
                          of =  "'id'"
                   myhiddens =  "[u'595']"
                hitset_empty =  'intbitset([])'
                           _ =  '<function unicode_gettext_wrapper at 0x7f18a36bbe60>'
                     verbose =  '0'

Frame search_pattern in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 2209
                    idx_unit =  '0'
                       bsu_m =  "'r'"
                     verbose =  '0'
                          ap =  '1'
                   myhiddens =  "[u'595']"
                       bsu_f =  "''"
                      bsu_pn =  "'*response*write*9915836*9154643*'"
                          ln =  "'en'"
                       bsu_o =  "'+'"
          basic_search_units =  '[[\'+\', \'"+response.write(9915836*9154643)+"\', \'\', \'r\']]'
                   user_info =  "UserInfo([{'referer': None, 'remote_host': '', 'uri': '/search', 'agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.63 Safari/537.36', 'remote_ip': '194.136.154.133'}, <CallbackDict {'settings': {}, 'uid': 0, 'id': 0}>, {}, {'precached_usestats': False, 'precached_usemessages': False, 'uid': -1, 'agent': '', 'uri': '', 'precached_usegroups': False, 'session': None, 'referer': '', 'precached_canseehiddenmarctags': False, 'precached_useadmin': F [...]
                           _ =  '<function unicode_gettext_wrapper at 0x7f18a36bba28>'
                       bsu_p =  '\'"+response.write(9915836*9154643)+"\''
                          wl =  '50000'
        basic_search_unit_hitset =  'intbitset([])'
              can_see_hidden =  'False'
        display_nearest_terms_box =  'True'
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18a39486d0>'
                           f =  "''"
                          of =  "'id'"
                           m =  "'r'"
        basic_search_units_hitsets =  '[]'
                           p =  '\'"+response.write(9915836*9154643)+"\''
                hitset_empty =  'intbitset([])'

Frame search_pattern_parenthesised in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 2306
-------------------------------------------------------------------------------
      2303     # sanity check: do not call parenthesised parser for search terms
      2304     # like U(1) but still call it for searches like ('U(1)' | 'U(2)'):
      2305     if not re_pattern_parens.search(re_pattern_parens_quotes.sub('_', p)):
----> 2306         return search_pattern(req, p, f, m, ap, of, verbose, ln, display_nearest_terms_box=display_nearest_terms_box, wl=wl)
      2307
      2308     # Try searching with parentheses
      2309     try:
-------------------------------------------------------------------------------
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18a39486d0>'
                     verbose =  '0'
                           f =  "''"
                          ln =  "'en'"
                          of =  "'id'"
                          wl =  '50000'
                           m =  "'r'"
                           p =  '\'"+response.write(9915836*9154643)+"\''
        spires_syntax_converter =  '<invenio.legacy.search_engine.query_parser.SpiresToInvenioSyntaxConverter instance at 0x7f18a2b958c0>'
                          ap =  '1'
                           _ =  '<function unicode_gettext_wrapper at 0x7f18a36bb758>'
         spires_syntax_query =  'False'
        display_nearest_terms_box =  'True'

Frame prs_advanced_search in /var/www/.virtualenvs/b2share/src/b2share/invenio/legacy/search_engine/__init__.py at line 6309
-------------------------------------------------------------------------------
      6306         # The error handling we want is different
      6307         raise
      6308     except:
----> 6309         register_exception(req=req, alert_admin=True)
      6310         if of.startswith("h"):
      6311             req.write(create_error_box(req, verbose=verbose, ln=ln))
      6312             perform_external_collection_search_with_em(req, cc, [p, p1, p2, p3], f, ec, verbose,
-------------------------------------------------------------------------------
                          em =  "''"
                          f1 =  "''"
                          f2 =  "''"
                          f3 =  "''"
                     verbose =  '0'
                         op2 =  "''"
        selected_external_collections_infos =  'None'
                      kwargs =  '{\'op1\': \'a\', \'op2\': \'\', \'cc\': u\'B2Share\', \'d2\': \'\', \'verbose\': 0, \'jrec\': 0, \'ln\': \'en\', \'selected_external_collections_infos\': None, \'m1\': \'r\', \'m3\': \'\', \'m2\': \'\', \'pl\': \'+author:"1" +title:"Mr." \', \'hosted_colls\': [], \'hosted_colls_potential_results_p\': False, \'hosted_colls_true_results\': None, \'dt\': \'\', \'colls_to_search\': [u\'B2Share\'], \'p2\': \'\', \'p3\': \'\', \'p1\': \'"+response.write(9915836*9154643)+"\', \'f\': \'fulltext\', \'ho [...]
                          ec =  '[]'
                          ap =  '1'
                         op1 =  "'a'"
                          ln =  "'en'"
                         req =  '<invenio.legacy.wsgi.SimulatedModPythonRequest object at 0x7f18a39486d0>'
                          cc =  "u'B2Share'"
                          m1 =  "'r'"
                          m3 =  "''"
                          m2 =  "''"
                          p3 =  "''"
                          wl =  '50000'
              len_results_p3 =  '0'
              len_results_p2 =  '0'
              len_results_p1 =  '0'
        results_in_any_collection =  'intbitset([])'
                           _ =  '<function unicode_gettext_wrapper at 0x7f18a36bbf50>'
                          p2 =  "''"
                       dummy =  '{\'uid\': 0, \'datetext2\': \'\', \'datetext1\': \'\', \'recid\': -1, \'d1y\': 0, \'tab\': \'\', \'d2\': \'\', \'id\': -1, \'d1\': \'\', \'d2y\': 0, \'sysnb\': \'\', \'only_hosted_colls_actual_or_potential_results_p\': False, \'jrec\': 0, \'colls_to_display\': [u\'B2Share\'], \'sysno\': \'\', \'hosted_colls_timeouts\': None, \'rg\': 10, \'d2m\': 0, \'rm\': \'\', \'d2d\': 0, \'pl\': \'+author:"1" +title:"Mr." \', \'hosted_colls_results\': None, \'wash_colls_debug\': \'\', \'sc\': 0, \'hosted_col [...]
                          p1 =  '\'"+response.write(9915836*9154643)+"\''
                           f =  "'fulltext'"
                          of =  "'id'"
                           p =  "'e'"
```

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
